import {
  Volume2,
  Brain,
  Stethoscope,
  Activity,
  Zap,
  BookOpen,
  MessageSquare,
  Sparkles,
  HeartPulse,
  Eye,
  Smile,
  Frown,
  Scale,
  ShieldAlert,
  Layers,
  Award,
  CheckCircle2,
  Clock,
  User,
  Users,
  Target,
  Compass,
  FileText
} from 'lucide-react';

// =========================================================================
// CLINICAL TESTS & PROTOCOLS CATALOG (+90 STANDARDIZED CLINICAL TESTS)
// Normes Algériennes et Arabes (CREAPSY / Universités Médicales) 🇩🇿
// =========================================================================
export const CLINICAL_TESTS_CATALOG = [
  {
    id: "ssi-4",
    code: "SSI-4",
    title_ar: "مقياس شدة التأتأة عند الأطفال والبالغين (Riley)",
    title_fr: "Stuttering Severity Instrument - 4th Edition",
    category: "orthophony",
    category_label: "طلاقة الكلام والتأتأة",
    age_range: "3 سنوات فما فوق (أطفال وبالغون)",
    duration: "20 - 30 دقيقة",
    source: "CREAPSY / الجامعات الجزائرية 🇩🇿",
    dimensions: ["تكرار المقاطع والأصوات", "الوقفات اللاإرادية (Blocks)", "الحركات الجسدية المصاحبة", "مدة التعثر بالثواني"],
    description: "الأداة المعيارية الذهبية لتقييم وقياس درجة شدة التأتأة وتحديد النسبة المئوية للتعثر أثناء القراءة والحديث العفوي.",
    cutoff: "طبيعي < 10 | خفيف: 11-17 | متوسط: 18-24 | شديد: 25-31 | حاد جداً: > 32",
    color: "from-amber-500 to-rose-600",
    icon: Volume2
  },
  {
    id: "test-artic-dz",
    code: "TEST-ARTIC-DZ",
    title_ar: "رائز فحص مخارج الأصوات والحروف باللهجة الجزائرية والفصحى",
    title_fr: "Test d'Articulation et de Phonologie (Normes DZ)",
    category: "orthophony",
    category_label: "النطق والأرطوفونيا",
    age_range: "3 - 10 سنوات",
    duration: "15 - 25 دقيقة",
    source: "CREAPSY / معيار جزائري 🇩🇿",
    dimensions: ["الأصوات الصامتة (أول/وسط/آخر الكلمة)", "التشويه والحذف والإبدال", "التمييز السمعي الفونولوجي", "المرونة اللسانية"],
    description: "فحص سريري شامل لكافة الفونيمات مع صور وبطاقات مكيفة مع البيئة والقاموس اللغوي الجزائري.",
    cutoff: "نسبة الدقة: طبيعي > 90% | تأخر نطقي خفيف: 75-89% | اضطراب نطقي دال: < 75%",
    color: "from-emerald-500 to-teal-600",
    icon: Stethoscope
  },
  {
    id: "teld-3",
    code: "TELD-3",
    title_ar: "اختبار التطور اللغوي الشامل (اللغة الاستقبالية والتعبيرية)",
    title_fr: "Test of Early Language Development (TELD-3)",
    category: "orthophony",
    category_label: "تأخر النمو اللغوي",
    age_range: "2 - 8 سنوات",
    duration: "25 - 35 دقيقة",
    source: "CREAPSY / الجامعات 🇩🇿",
    dimensions: ["اللغة الاستقبالية والفهم", "اللغة التعبيرية والتركيب", "القاموس الدلالي والمفردات", "النحو والصرف"],
    description: "يقيس بدقة العمر اللغوي للطفل مقارنة بعمره الزمني وتحديد نسبة التأخر في اكتساب مهارات التخاطب.",
    cutoff: "معامل لغوي: طبيعي 90-110 | تأخر بسيط 80-89 | تأخر متوسط 70-79 | تأخر حاد < 70",
    color: "from-sky-600 to-blue-700",
    icon: MessageSquare
  },
  {
    id: "alou-r",
    code: "ALOU-R",
    title_ar: "اختبار طلاقة القراءة السريعة والتحليل الصوتي (L'Alouette-R)",
    title_fr: "L'Alouette-R (Épreuve de lecture de texte)",
    category: "orthophony",
    category_label: "القراءة وصعوبات التعلم",
    age_range: "6 - 16 سنة (أطفال ومراهقون)",
    duration: "5 دقائق (مقننة بدقة)",
    source: "CREAPSY / الجامعات 🇩🇿",
    dimensions: ["سرعة القراءة (الكلمات الصحيحة بالدقيقة)", "مؤشر دقة القراءة والتهجئة", "زمن القراءة الكلي", "تحديد العمر القرائي"],
    description: "الاختبار المعياري الأكثر شهرة في الأرطوفونيا لتقييم سرعة ودقة القراءة وتشخيص عسر القراءة الفونولوجي والسطحي.",
    cutoff: "عمر قرائي مطابق للعمر الزمني: طبيعي | فارق > 18 شهراً: مؤشر ديسلكسيا دال",
    color: "from-amber-600 to-emerald-600",
    icon: BookOpen
  },
  {
    id: "apha-r",
    code: "APHA-R",
    title_ar: "رائز فحص الحبسة الكلامية وفقدان اللغة المكتسبة (APHA-R)",
    title_fr: "Test pour l'examen de l'aphasie (APHA-R)",
    category: "orthophony",
    category_label: "الحبسة والأمراض العصبية",
    age_range: "مراهقون وبالغون (15 سنة فما فوق)",
    duration: "30 - 45 دقيقة",
    source: "CREAPSY / المستشفيات الجامعية 🇩🇿",
    dimensions: ["التعبير التلقائي وسلاسة النطق", "الفهم الشفهي للأوامر البسيطة والمعقدة", "التسمية واسترجاع الكلمات", "التكرار اللفظي والقراءة والكتابة"],
    description: "فحص سريري دقيق لحبسة بروكا وحبسة فيرنيكي والحبسة الكلية بعد الجلطات الدماغية ورضوض الرأس.",
    cutoff: "مؤشر عجز حاد < 40% | متوسط 41-70% | خفيف 71-85% | طبيعي > 85%",
    color: "from-rose-600 to-indigo-700",
    icon: HeartPulse
  },
  {
    id: "hdae",
    code: "HDAE",
    title_ar: "مقياس بوسطن لتشخيص وتقييم الحبسة الكلامية (HDAE / BDAE)",
    title_fr: "Échelle d'évaluation de l'aphasie (Boston BDAE)",
    category: "orthophony",
    category_label: "الحبسة العصبية",
    age_range: "مراهقون وبالغون",
    duration: "45 - 60 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["طلاقة الخطاب والتنغيم", "الفهم السمعي والمفردات", "التسمية البصرية استجابة للمثيرات", "القراءة الجهرية وفهم المكتوب"],
    description: "البطارية التشخيصية الكلاسيكية المعتمدة في مصالح الأعصاب لتحديد النمط السريري للحبسة وتحديد أهداف التأهيل العصبي اللغوي.",
    cutoff: "تحديد نمط الحبسة (Broca, Wernicke, Conduction, Transcorticale)",
    color: "from-indigo-600 to-purple-800",
    icon: Brain
  },
  {
    id: "bepl-a",
    code: "BEPL-A",
    title_ar: "البطارية السيكولسانية لتقييم لغة الطفل - المستوى أ (BEPL-A)",
    title_fr: "Batterie d'évaluation psycholinguistique A",
    category: "orthophony",
    category_label: "اللغة والنمو الفونولوجي",
    age_range: "2.5 - 4 سنوات (الطفولة المبكرة)",
    duration: "25 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الوعي بالفونيمات الأولية", "فهم التراكيب النحوية البسيطة", "الرصيد المعجمي الأولي", "التقليد الصوتي والحركي"],
    description: "تقييم مبكر للبنى اللغوية الأولى للكشف عن التأخر الأولي أو الاضطراب النمائي للغة (Dysphasie).",
    cutoff: "درجة معيارية: طبيعي ضمن المتوسط | انحراف معياري < -1.5 SD: تأخر نمائي يستلزم التدخل",
    color: "from-teal-500 to-cyan-600",
    icon: Smile
  },
  {
    id: "bepl-b",
    code: "BEPL-B",
    title_ar: "البطارية السيكولسانية لتقييم لغة الطفل - المستوى ب (BEPL-B)",
    title_fr: "Batterie d'évaluation psycholinguistique B",
    category: "orthophony",
    category_label: "اللغة والتركيب النحوي",
    age_range: "4 - 7 سنوات",
    duration: "30 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["التركيب النحوي للجمل المعقدة", "الصرف وتصريف الأفعال", "المعالجة الفونولوجية السريعة", "إنتاج السرد القصصي"],
    description: "تقييم معمق للمهارات اللغوية المتقدمة قبل الالتحاق بالمدرسة الابتدائية لضمان الجاهزية القرائية.",
    cutoff: "معيار مقنن: < Percentile 15 يستدعي كفالة أرطوفونية متخصصة",
    color: "from-teal-600 to-blue-700",
    icon: Layers
  },
  {
    id: "bo-borelli",
    code: "BO",
    title_ar: "اختبار بوريلي-أوليرون للغة والأداء للأطفال الصم وضعاف السمع (Borelli-Oléron)",
    title_fr: "Test de langage et de niveau mental Borelli-Oléron",
    category: "orthophony",
    category_label: "الإعاقة السمعية واللغة",
    age_range: "4 - 9 سنوات",
    duration: "30 دقيقة",
    source: "CREAPSY / مدارس الصم 🇩🇿",
    dimensions: ["التجريد والتصنيف البصري غير اللفظي", "فهم الإشارات والإيماءات", "القراءة الشفوية وقراءة الشفاه", "الذاكرة البصرية التتابعية"],
    description: "رائز رائد مخصص للأطفال الصم أو ذوي الاضطرابات اللغوية الشديدة لقياس القدرات العقلية دون الاعتماد على القناة السمعية.",
    cutoff: "تحديد العمر العقلي غير اللفظي والعمر النطقي",
    color: "from-violet-600 to-pink-600",
    icon: Eye
  },
  {
    id: "do80",
    code: "DO80",
    title_ar: "اختبار التسمية الشفهية للصور (DO 80 - Deloche & Hannequin)",
    title_fr: "Dénomination orale d'images (DO 80)",
    category: "orthophony",
    category_label: "استرجاع المعجم والتسمية",
    age_range: "مراهقون وبالغون وكبار السن",
    duration: "15 دقيقة",
    source: "CREAPSY / المستشفيات 🇩🇿",
    dimensions: ["زمن الوصول إلى الكلمة (Latency)", "أخطاء التبديل الصوتي (Paraphasies)", "أخطاء التبديل الدلالي", "استجابة التلميح الصوتي والدلالي"],
    description: "80 لوحة صورية بالأبيض والأسود لتقييم عسر التسمية (Anomie) في الحبسة والخرف والاضطرابات المعرفية.",
    cutoff: "طبيعي: خطأ <= 3 صور | عسر تسمية خفيف: 4-8 أخطاء | عسر تسمية دال: > 8 أخطاء",
    color: "from-blue-600 to-indigo-700",
    icon: Sparkles
  },
  {
    id: "elo",
    code: "ELO",
    title_ar: "تقييم اللغة الشفهية عند الطفل (ELO - Khomsi)",
    title_fr: "Évaluation du langage oral (ELO)",
    category: "orthophony",
    category_label: "اللغة الاستقبالية والتعبيرية",
    age_range: "3 - 8 سنوات",
    duration: "20 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["فهم المفردات المعجمية", "فهم التراكيب النحوية", "إنتاج الجمل وصياغة الأفكار", "الذاكرة السمعية المباشرة للأصوات"],
    description: "بطارية فرنسية عربية سريعة ومقننة توفر بروفيلاً بيانياً لمستوى الطفل اللغوي ونقاط القوة والضعف.",
    cutoff: "انحراف معياري < -1.65 SD يدل على عجز لغوي دال",
    color: "from-emerald-600 to-cyan-600",
    icon: Stethoscope
  },
  {
    id: "l2ma",
    code: "L2MA",
    title_ar: "بطارية فحص اللغة الشفهية، اللغة المكتوبة، الذاكرة والانتباه (L2MA-2)",
    title_fr: "Batterie L2MA (Langage oral, écrit, mémoire, attention)",
    category: "orthophony",
    category_label: "اللغة والتعلم المتكامل",
    age_range: "8 - 15 سنة (أطفال ومراهقون)",
    duration: "45 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الطلاقة اللفظية المعجمية والفونيمية", "القراءة الصامتة والجهرية", "الإملاء والتحليل الإملائي", "الذاكرة العاملة اللفظية"],
    description: "البطارية المرجعية الشاملة للأخصائيين الأرطوفونيين لتقييم صعوبات التعلم الأكاديمية واللغة عند المتمدرسين.",
    cutoff: "تحديد نمط عسر التعلم (ديسلكسيا، ديسورثوغرافيا، أو تأخر لغوي متراكب)",
    color: "from-sky-700 to-indigo-800",
    icon: BookOpen
  },
  {
    id: "vocim",
    code: "VOCIM",
    title_ar: "اختبار المفردات والمعجم اللغوي المصور للأطفال (VOCIM)",
    title_fr: "Test de vocabulaire en images (VOCIM)",
    category: "orthophony",
    category_label: "الرصيد اللغوي والمفردات",
    age_range: "3 - 9 سنوات",
    duration: "15 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["المفردات الاستقبالية (الإشارة للصورة)", "المفردات التعبيرية (تسمية الصورة)", "تصنيف الحقول الدلالية", "عمر اكتساب المفردة"],
    description: "يقيس بدقة سعة المخزن المعجمي الدلالي للطفل وتحديد ما إذا كان الفقر اللغوي بسبب نقص التحفيز البيئي أو اضطراب نمائي.",
    cutoff: "طبيعي: مئين 25-75 | فقر معجمي خفيف: مئين 10-24 | تأخر حاد: أقل من المئين 10",
    color: "from-amber-500 to-teal-600",
    icon: Smile
  },
  {
    id: "zareki-r",
    code: "ZAREKI-R",
    title_ar: "بطارية فحص ومعالجة الأعداد والحساب للأطفال (ZAREKI-R - von Aster)",
    title_fr: "Batterie pour l'évaluation du traitement des nombres et du calcul",
    category: "orthophony",
    category_label: "عسر الحساب (Dyscalculie)",
    age_range: "6 - 11 سنة (سنوات الابتدائي)",
    duration: "30 - 45 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["قراءة وكتابة الأعداد رمزياً ولفظياً", "العد التنازلي والقفز العددي", "تمثيل خط الأعداد الذهني", "العمليات الحسابية الذهنية والمكتوبة", "المسائل اللفظية الرياضية"],
    description: "الأداة العيادية المعتمدة لتشخيص الديسكلكوليا وتحديد العجز في معالجة الكميات أو الخط العددي الذهني.",
    cutoff: "معيار القطع: درجة أقل من المئين 15 في 3 اختبارات فرعية تؤكد عسر الحساب",
    color: "from-purple-600 to-rose-600",
    icon: Zap
  },
  {
    id: "o52",
    code: "O52",
    title_ar: "بروتوكول O52 لتقييم وفحص الوظائف اللغوية والتعبيرية",
    title_fr: "Protocole d'évaluation orthophonique O52",
    category: "orthophony",
    category_label: "الفحص الأرطوفوني الشامل",
    age_range: "أطفال سن التمدرس",
    duration: "30 دقيقة",
    source: "Université Algérienne / CREAPSY 🇩🇿",
    dimensions: ["المستوى الصوتي الفونولوجي", "المستوى التركيبي الصرفي", "المستوى الدلالي والمعجمي", "المستوى التداولي البراغماتي"],
    description: "بروتوكول جامعي جزائري معتمد في أطروحات الماجستير والعيادات الأرطوفونية لتقييم المهارات اللغوية الرباعية.",
    cutoff: "ملف سريري وصفي كمي ونوعي",
    color: "from-teal-600 to-indigo-700",
    icon: FileText
  },
  {
    id: "n-eel",
    code: "N-EEL",
    title_ar: "الاختبارات الجديدة لتقييم اللغة عند الأطفال (N-EEL - Chevrie-Muller)",
    title_fr: "Nouvelles épreuves pour l'évaluation du langage (N-EEL)",
    category: "orthophony",
    category_label: "التقييم اللغوي المقنن",
    age_range: "3.5 - 8 سنوات",
    duration: "35 دقيقة",
    source: "Université / CREAPSY 🇩🇿",
    dimensions: ["فهم التراكيب النحوية المعقدة", "تكرار الجمل والكلمات غير المألوفة", "استيعاب المتضادات والمترادفات", "إنتاج القصة المصورة"],
    description: "معيار إكلينيكي ممتاز لقياس التطور اللغوي بدقة وتحديد نوع ونسبة التأخر مقارنة بالأقران في نفس الفئة العمرية.",
    cutoff: "درجة معيارية Z-Score: طبيعي بين -1 و +1 | عجز نمائي: Z < -2.0",
    color: "from-blue-500 to-teal-700",
    icon: MessageSquare
  },
  {
    id: "mta",
    code: "MTA",
    title_ar: "بروتوكول MTA لفحص اضطرابات النطق والكلام والحبسة",
    title_fr: "Protocole MTA d'évaluation du langage et de l'articulation",
    category: "orthophony",
    category_label: "النطق والحبسة",
    age_range: "أطفال وبالغون",
    duration: "30 دقيقة",
    source: "Université / CREAPSY 🇩🇿",
    dimensions: ["فحص الحركة النطقية", "التمييز السمعي للأصوات المتقاربة", "الفهم التعبيري", "الكتابة والقراءة الإملائية"],
    description: "بروتوكول سريري جامع يدمج بين الفحص العضوي الوظيفي ومظاهر الاضطراب اللغوي الوظيفي.",
    cutoff: "تقييم سريري نوعي",
    color: "from-cyan-600 to-emerald-700",
    icon: Stethoscope
  },
  {
    id: "reor",
    code: "REOR",
    title_ar: "حقيبة مواد إعادة التأهيل الأرطوفوني واللغوي (REOR)",
    title_fr: "Matériel de rééducation orthophonique (REOR)",
    category: "orthophony",
    category_label: "إعادة التأهيل الأرطوفوني",
    age_range: "مراهقون وبالغون",
    duration: "جلسات علاجية دورية",
    source: "CREAPSY 🇩🇿",
    dimensions: ["تمارين التسمية والبحث الدلالي", "تمارين بناء الجمل وتصحيح الصرف", "تمارين الطلاقة اللفظية والقراءة العلاجية"],
    description: "أداة تدريبية وعلاجية للأخصائيين الأرطوفونيين لتأهيل حالات الحبسة، تأخر اللغة، والاضطرابات العصبية النطقية.",
    cutoff: "مؤشر تطور الأداء عبر الحصص",
    color: "from-amber-600 to-orange-700",
    icon: Award
  },
  {
    id: "mt-86",
    code: "MT-86",
    title_ar: "بروتوكول مونتريال-تولوز لفحص الحبسة وفقدان القدرة على الكلام (MT-86)",
    title_fr: "Protocole Montréal-Toulouse d'examen de l'aphasie (MT-86)",
    category: "orthophony",
    category_label: "الحبسة والأمراض العصبية",
    age_range: "البالغون والمسنون بعد السكتات الدماغية",
    duration: "45 دقيقة",
    source: "CREAPSY / المستشفيات 🇩🇿",
    dimensions: ["الكلام التلقائي والوصف الصوري", "الفهم الشفهي والمكتوب للكلمات والجمل", "التكرار اللفظي للمقاطع والعبارات", "التسمية واستدعاء المفردات"],
    description: "البطارية الفرنسية المرجعية الأوسع انتشاراً في المستشفيات لتقييم العجز اللغوي العصبي ومتابعة التعافي بعد الإصابات الدماغية.",
    cutoff: "تصنيف نوع الحبسة وتحديد مؤشر الشدة",
    color: "from-indigo-600 to-purple-700",
    icon: HeartPulse
  },
  {
    id: "grbas",
    code: "GRBAS",
    title_ar: "مقياس هيرانو لتقييم جودة وبحة الصوت الحنجري (GRBAS Scale)",
    title_fr: "Échelle d'évaluation perceptive de la voix (GRBAS)",
    category: "orthophony",
    category_label: "أمراض الصوت والحنجرة (Phoniatrie)",
    age_range: "كافة الأعمار (أطفال وبالغون)",
    duration: "10 - 15 دقيقة",
    source: "CREAPSY / طب الأنف والأذن والحنجرة 🇩🇿",
    dimensions: ["Grade: الدرجة الكلية للبحة", "Roughness: الخشونة والحرشفة", "Breathiness: التسريب الهوائي", "Asthenia: الوهن والضعف الصوتي", "Strain: التشنج والضغط العضلي"],
    description: "المقياس السمعي الإدراكي المعياري لتقييم بحة الصوت وتشخيص العقيدات واللحميات على الحبال الصوتية والوهن الحنجري.",
    cutoff: "0: طبيعي تماماً | 1: بحة طفيفة | 2: بحة متوسطة | 3: بحة شديدة جداً",
    color: "from-emerald-500 to-teal-700",
    icon: Volume2
  },
  {
    id: "cars-2",
    code: "CARS-2",
    title_ar: "مقياس تقدير التوحد الطفولي (نسخة المعيار الجزائري والعربي)",
    title_fr: "Childhood Autism Rating Scale - 2nd Edition (CARS-2)",
    category: "autism",
    category_label: "اضطرابات طيف التوحد",
    age_range: "2 - 14 سنة",
    duration: "30 - 45 دقيقة",
    source: "CREAPSY / الجامعات 🇩🇿",
    dimensions: ["العلاقات مع الناس", "التقليد والتواصل البصري", "الاستجابة الانفعالية", "استخدام الجسد والأشياء", "التواصل اللفظي وغير اللفظي"],
    description: "مقياس تشخيصي إكلينيكي مكون من 15 بنداً سلوكياً لفرز وتصنيف درجات طيف التوحد بدقة معيارية.",
    cutoff: "< 30: سليم غير توحدي | 30 - 36.5: طيف توحد خفيف إلى متوسط | >= 37: طيف توحد شديد",
    color: "from-blue-600 to-indigo-600",
    icon: Brain
  },
  {
    id: "m-chat",
    code: "M-CHAT",
    title_ar: "الاستبيان المبكر المعدل للكشف عن التوحد لدى الرضع (M-CHAT-R/F)",
    title_fr: "Modified Checklist for Autism in Toddlers (M-CHAT)",
    category: "autism",
    category_label: "الكشف والفرز المبكر للتوحد",
    age_range: "16 - 30 شهراً (الرضع والطفولة المبكرة)",
    duration: "10 دقائق",
    source: "CREAPSY / Université 🇩🇿",
    dimensions: ["التفاعل والمشاركة البصرية (Joint Attention)", "الاستجابة للنداء بالاسم", "الإشارة بالسبابة للطلب أو الاهتمام", "اللعب التخيلي الرمزي"],
    description: "أداة المسح والفرز الأولى عالمياً الموصى بها من منظمة الصحة العالمية للكشف المبكر عن سمات التوحد قبل عمر سنتين ونصف.",
    cutoff: "0-2 نقاط: خطورة منخفضة | 3-7 نقاط: خطورة متوسطة تستلزم مقابلة المتابعة | 8-20 نقطة: خطورة مرتفعة تستدعي تشخيصاً شاملاً",
    color: "from-emerald-500 to-teal-600",
    icon: Smile
  },
  {
    id: "adi-r",
    code: "ADI-R",
    title_ar: "المقابلة التشخيصية المعمقة للتوحد مع الأولياء (ADI-R)",
    title_fr: "Autism Diagnostic Interview-Revised (ADI-R)",
    category: "autism",
    category_label: "التشخيص الإكلينيكي المعمق",
    age_range: "من عمر سنتين حتى البلوغ",
    duration: "90 - 120 دقيقة",
    source: "CREAPSY / Université 🇩🇿",
    dimensions: ["التفاعل الاجتماعي المتبادل وتاريخ الطفولة", "التواصل واللغة اللفظية وغير اللفظية", "الأنماط السلوكية المقيدة والنمطية", "مظاهر التطور قبل سن 36 شهراً"],
    description: "المقابلة المعيارية الذهبية مع أولياء الأمور للتشخيص السريري المعتمد وفق معايير DSM-5 و ICD-11.",
    cutoff: "تجاوز عتبات القطع في المجالات الثلاثة يؤكد التشخيص السريري لاضطراب طيف التوحد",
    color: "from-indigo-600 to-violet-800",
    icon: Users
  },
  {
    id: "ados-2",
    code: "ADOS-2",
    title_ar: "جدول الملاحظة التشخيصية المعيارية للتوحد (ADOS-2)",
    title_fr: "Autism Diagnostic Observation Schedule - 2nd Edition",
    category: "autism",
    category_label: "الملاحظة السريرية المباشرة",
    age_range: "من 12 شهراً إلى البالغين (وفق 5 مستويات)",
    duration: "45 - 60 دقيقة",
    source: "CREAPSY / Université 🇩🇿",
    dimensions: ["التواصل الاجتماعي الوجداني (SA)", "السلوك المقيد والمتكرر (RRB)", "جودة المشاركة الاجتماعية", "الاستجابة لطلب الانتباه المشترك"],
    description: "الأداة الملاحظاتية القياسية الأولى عالمياً لتقييم التوحد عبر مواقف لعب وأنشطة حوارية موجهة حسب العمر اللغوي.",
    cutoff: "درجة القطع المركبة (Comparison Score 1-10): 1-4 طفيف/حدودي | 5-7 طيف توحد | 8-10 توحد شديد",
    color: "from-blue-600 to-purple-600",
    icon: Eye
  },
  {
    id: "ecan",
    code: "ECAN",
    title_ar: "مقياس تقييم السلوك التوحدي لدى الرضيع والطفل الصغير (ECAN)",
    title_fr: "Évaluation du comportement autistique du nourrisson (ECAN)",
    category: "autism",
    category_label: "التوحد المبكر والرضع",
    age_range: "6 أشهر - 24 شهراً",
    duration: "20 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["التواصل البصري والابتسامة الاجتماعية", "الهدوء والسكينة أثناء الحمل والاحتضان", "الاستجابة الصوتية لمناغاة الأم", "الاهتمام بالأشياء المتحركة"],
    description: "رائز فرنسي جزائري رائد لرصد العلامات الإنذارية المبكرة جداً للتوحد لدى الرضع في عامهم الأول.",
    cutoff: "درجة مرتفعة تستوجب برنامج تدخل مبكر فوري",
    color: "from-pink-500 to-rose-600",
    icon: Smile
  },
  {
    id: "ecar",
    code: "ECAR",
    title_ar: "مقياس تقييم السلوك التوحدي لدى الأطفال المتمدرسين (ECAR)",
    title_fr: "Évaluation du comportement autistique de l'enfant (ECAR)",
    category: "autism",
    category_label: "السلوك التوحدي والتكيف",
    age_range: "2 - 12 سنة",
    duration: "25 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الانسحاب الاجتماعي والانعزال", "المقاومة الشديدة للتغيير", "الحركات التكرارية والاهتزاز", "الاضطرابات الحسية تجاه الأصوات والملامس"],
    description: "مقياس عيادي لملاحظة السلوك في الفصول المدمجة والعيادات لحساب درجة الشدة وتتبع التطور العلاجي.",
    cutoff: "تصنيف كمي لدرجة التوحد ومستوى الاستقلالية",
    color: "from-indigo-600 to-teal-600",
    icon: Activity
  },
  {
    id: "vineland",
    code: "VINELAND",
    title_ar: "مقياس فاينلاند للسلوك التكيفي والمهارات اليومية (Vineland-II)",
    title_fr: "Vineland Adaptive Behavior Scales - 2nd Edition",
    category: "autism",
    category_label: "السلوك التكيفي والاستقلالية",
    age_range: "من الولادة حتى 90 سنة",
    duration: "45 دقيقة",
    source: "CREAPSY / Université 🇩🇿",
    dimensions: ["مهارات التواصل (استقبالي، تعبيري، كتابي)", "مهارات الحياة اليومية (العناية الشخصية، المنزلية، المجتمعية)", "التنشئة الاجتماعية (العلاقات، اللعب، التكيف)", "المهارات الحركية (الكبرى والدقيقة)"],
    description: "الأداة المعيارية الدولية لتحديد مستوى التكيف الوظيفي وتشخيص درجات القصور الذهني وأولويات خطة التأهيل الفردية.",
    cutoff: "درجة معيارية: < 70 قصور تكيفي دال | 70-84 حدّي منخفض | 85-115 أداء تكيفي طبيعي",
    color: "from-emerald-600 to-teal-800",
    icon: CheckCircle2
  },
  {
    id: "ecaa-echa",
    code: "ECAA-ECHA",
    title_ar: "مقياس السلوكيات العدوانية الموجهة نحو الذات والآخرين (ECAA / ECHA)",
    title_fr: "Échelles de comportements auto et hétéro-agressifs",
    category: "autism",
    category_label: "تعديل السلوك والعدوانية",
    age_range: "أطفال، مراهقون، وبالغون",
    duration: "20 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["إيذاء الذات (ضرب الرأس، العض، الخدش)", "الاعتداء على الآخرين (العض، الضرب، الدفع)", "تخريب الممتلكات والأثاث", "نوبات الغضب الحادة والمثيرات المحفزة"],
    description: "أداة عيادية حيوية لتحليل الوظيفة السلوكية وتصميم خطط الدعم السلوكي الإيجابي (PBS) لمرضى التوحد والإعاقات النمائية.",
    cutoff: "مؤشر شدة وتكرار السلوك لتحديد التدابير الوقائية",
    color: "from-rose-600 to-red-700",
    icon: ShieldAlert
  },
  {
    id: "gars-3",
    code: "GARS-3",
    title_ar: "مقياس جليام لتشخيص اضطراب التوحد - الإصدار الثالث (GARS-3)",
    title_fr: "Gilliam Autism Rating Scale - 3rd Edition",
    category: "autism",
    category_label: "اضطرابات طيف التوحد",
    age_range: "3 - 22 سنة",
    duration: "20 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["السلوكيات النمطية المقيدة", "التفاعل الاجتماعي", "التواصل الاجتماعي", "الاستجابات العاطفية"],
    description: "أداة تشخيصية سريعة مبنية على معايير DSM-5 لحساب معامل التوحد ونسبة الاحتمالية السريرية.",
    cutoff: "معامل التوحد (Autism Index): < 54 مستبعد | 55-70 محتمل | >= 71 مؤكد بدرجة عالية",
    color: "from-teal-600 to-cyan-700",
    icon: Brain
  },
  {
    id: "conners-3",
    code: "CONNERS-3",
    title_ar: "مقياس كونرز لفرط الحركة وتشتت الانتباه والاندفاعية (Conners-3)",
    title_fr: "Conners 3rd Edition (ADHD Assessment)",
    category: "tdah_apprentissage",
    category_label: "فرط الحركة وتشتت الانتباه",
    age_range: "6 - 18 سنة (أطفال ومراهقون)",
    duration: "20 دقيقة",
    source: "CREAPSY / معيار مقنن 🇩🇿",
    dimensions: ["تشتت الانتباه وقصور التركيز", "فرط النشاط الحركي والتململ", "الاندفاعية والتسرع السلوكي", "العلاقات مع الأقران والأسرة والأداء الدراسي"],
    description: "المقياس العالمي الأول الموجه للأولياء والمعلمين لتشخيص أنماط اضطراب TDAH الثلاثة (المركب، الغافل، والاندفاعي).",
    cutoff: "T-Score: < 60 طبيعي | 60-64 حدّي مرتفع | 65-69 مرتفع دال سريرياً | >= 70 مرتفع جداً",
    color: "from-purple-600 to-pink-600",
    icon: Activity
  },
  {
    id: "d2",
    code: "D2",
    title_ar: "اختبار شطب الحروف لقياس الانتباه والتركيز البصري (Test d'attention D2 / D2-R)",
    title_fr: "Test d'attention concentrée d2 de Brickenkamp",
    category: "tdah_apprentissage",
    category_label: "الانتباه والسرعة الإدراكية",
    age_range: "9 - 60 سنة",
    duration: "8 دقائق مقننة بدقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["سرعة المعالجة البصرية الإجمالية (TN)", "مؤشر جودة ودقة التركيز (CP)", "نسبة أخطاء الحذف والإغفال (E1)", "نسبة أخطاء الإرباك والخلط (E2)"],
    description: "اختبار ورقي سريري كلاسيكي يقيس بدقة قدرة الدماغ على تركيز الانتباه واستبعاد المشتتات تحت ضغط الوقت.",
    cutoff: "مئين: < 16 ضعف تركيز شديد | 16-84 ضمن المتوسط الطبيعي | > 84 قدرة تركيز ممتازة",
    color: "from-amber-600 to-rose-600",
    icon: Zap
  },
  {
    id: "stroop",
    code: "STROOP",
    title_ar: "اختبار شتروب للمرونة المعرفية وكبح الاستجابة الاندفاعية (Test de Stroop)",
    title_fr: "Test de Stroop (Inhibition cognitive et attention)",
    category: "tdah_apprentissage",
    category_label: "الوظائف التنفيذية والكبح",
    age_range: "7 سنوات فما فوق (أطفال وبالغون)",
    duration: "10 دقائق",
    source: "CREAPSY 🇩🇿",
    dimensions: ["قراءة الكلمات الملونة (المرحلة 1)", "تسمية الألوان (المرحلة 2)", "مرحلة التعارض والتداخل (Interference)", "مؤشر كبح الاستجابة التلقائية"],
    description: "المقياس النيوروبسيكولوجي الأساسي لقياس وظائف الفص الجبهي والقدرة على مقاومة التشتت والاندفاعية.",
    cutoff: "مؤشر تداخل شتروب (Interference Score): تراجع دال > 1.5 انحراف معياري يشير لخلل في الكبح التنفيذي",
    color: "from-purple-600 to-indigo-700",
    icon: Target
  },
  {
    id: "tea-ch",
    code: "TEA-CH",
    title_ar: "بطارية تقييم الانتباه اليومي للأطفال (TEA-Ch - Manly et al.)",
    title_fr: "Test of Everyday Attention for Children (TEA-Ch)",
    category: "tdah_apprentissage",
    category_label: "الانتباه المتعدد والذاكرة",
    age_range: "6 - 16 سنة",
    duration: "45 دقيقة",
    source: "CREAPSY / Base comp 🇩🇿",
    dimensions: ["الانتباه الانتقائي البصري (البحث في الفضاء)", "الانتباه المستمر السمعي (عد الأصوات)", "الانتباه المنقسم والتنقل بين المهام (Dual Task)", "التحكم في الاندفاع الحركي"],
    description: "بطارية ألعاب عيادية ممتازة تقيس كافة أبعاد الانتباه المستمر والانتقائي والمقسم في بيئة مرحة للأطفال.",
    cutoff: "معيار إكلينيكي: رصد الفصوص العصبية المسببة لصعوبات التركيز",
    color: "from-blue-600 to-cyan-600",
    icon: Compass
  },
  {
    id: "ai-matching",
    code: "AI",
    title_ar: "اختبار مطابقة الصور والانتباه الإدراكي البصري (Test d'appariement d'images)",
    title_fr: "Test d'appariement d'images (MFFT / Matching)",
    category: "tdah_apprentissage",
    category_label: "الاندفاعية الإدراكية",
    age_range: "أطفال ومراهقون (6 - 15 سنة)",
    duration: "15 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["زمن الاستجابة الأولية (التأني مقابل التسرع)", "عدد الأخطاء قبل الوصول للمطابق", "أسلوب التفكير التأملي مقابل الاندفاعي"],
    description: "يقيس بدقة ما إذا كان الطفل يمتلك نمطاً إدراكياً تأملياً متأنياً أو نمطاً اندفاعياً متسرعاً يؤثر على تحصيله المدرسي.",
    cutoff: "تصنيف النمط: تأملي (زمن طويل/أخطاء قليلة) أو اندفاعي (زمن قصير/أخطاء كثيرة)",
    color: "from-teal-600 to-emerald-700",
    icon: Eye
  },
  {
    id: "ecs-2",
    code: "ECS-II",
    title_ar: "بطارية تقييم الكفاءات والمهارات المدرسية - المستوى الثاني (ECS-II)",
    title_fr: "Évaluation des compétences scolaires II",
    category: "tdah_apprentissage",
    category_label: "صعوبات التعلم الأكاديمية",
    age_range: "7 - 9 سنوات (الطور الابتدائي)",
    duration: "30 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["استيعاب المفاهيم الرياضية والهندسية", "التهجئة والدقة الإملائية", "فهم الأسئلة والتعليمات المكتوبة", "التنظيم والمنهجية في حل التمارين"],
    description: "رائز تربوي نفسي لتحديد الفجوة بين قدرات الطفل العقلية ومستواه الأكاديمي الصفي.",
    cutoff: "تأخر دراسي نوعي مقابل تأخر عام",
    color: "from-amber-600 to-orange-700",
    icon: BookOpen
  },
  {
    id: "ecs-3",
    code: "ECS-III",
    title_ar: "بطارية تقييم الكفاءات والمهارات المدرسية - المستوى الثالث (ECS-III)",
    title_fr: "Évaluation des compétences scolaires III",
    category: "tdah_apprentissage",
    category_label: "التحصيل والمهارات المدرسية",
    age_range: "9 - 12 سنة",
    duration: "35 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الاستدلال المنطقي الرياضي", "التحليل اللغوي والتعبير الكتابي", "استخلاص الأفكار الرئيسية من النصوص", "سرعة الإنجاز"],
    description: "تشخيص دقيق لنقاط الضعف الأكاديمية في مرحلة التعليم الابتدائي المتقدم للانتقال للمتوسط.",
    cutoff: "تحديد احتياجات برنامج الدعم التربوي المكيف (PEI)",
    color: "from-orange-600 to-indigo-700",
    icon: Award
  },
  {
    id: "tms",
    code: "TMS",
    title_ar: "اختبار النضج والجاهزية المدرسية للالتحاق بالصف الأول (TMS)",
    title_fr: "Test de maturité scolaire (TMS)",
    category: "tdah_apprentissage",
    category_label: "النضج والجاهزية المدرسية",
    age_range: "5 - 6.5 سنوات (التحضيري والابتدائي)",
    duration: "25 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["النضج اللغوي والمفاهيم قبل العددية", "التآزر البصري الحركي ورسم الخطوط", "القدرة على الانتباه الجماعي والامتثال للتعليمات", "النضج الانفعالي والاستقلالية عن الوالدين"],
    description: "يحدد ما إذا كان الطفل مستعداً للاندماج في التعليم النظامي أو يحتاج عاماً إضافياً في القسم التحضيري.",
    cutoff: "مؤشر الجاهزية: مؤهل للتمدرس / يحتاج متابعة تحضيرية / غير ناضج مدرسياً",
    color: "from-emerald-600 to-blue-700",
    icon: CheckCircle2
  },
  {
    id: "ddcp",
    code: "DDCP",
    title_ar: "أداة التشخيص والمعالجة المعرفية لصعوبات التعلم (DDCP)",
    title_fr: "Outil de diagnostic et de remédiation cognitive (DDCP)",
    category: "tdah_apprentissage",
    category_label: "العلاج المعرفي والتعلم",
    age_range: "أطفال ومراهقون",
    duration: "جلسات تقييم وتدريب",
    source: "CREAPSY 🇩🇿",
    dimensions: ["استراتيجيات التذكر والتنظيم", "التخطيط وحل المشكلات المعرفية", "تطوير ما وراء المعرفة (Métacognition)"],
    description: "أداة علاجية متكاملة لتدريب الطلاب ذوي صعوبات التعلم على بناء استراتيجيات تفكير فعالة.",
    cutoff: "معدل اكتساب الاستراتيجيات الذهنية",
    color: "from-purple-600 to-pink-700",
    icon: Layers
  },
  {
    id: "bhk-dz",
    code: "BHK-DZ",
    title_ar: "مقياس عسر الكتابة السريعة والخط الرديء للأطفال (BHK Échelle d'écriture)",
    title_fr: "Échelle d'évaluation rapide de l'écriture chez l'enfant (BHK-DZ)",
    category: "tdah_apprentissage",
    category_label: "عسر الكتابة (Dysgraphie)",
    age_range: "6 - 12 سنة (من الابتدائي إلى المتوسط)",
    duration: "5 دقائق كتابة مقننة",
    source: "CREAPSY / معيار جزائري 🇩🇿",
    dimensions: ["سرعة الكتابة وعدد الحروف المكتوبة في 5 دقائق", "حجم الحروف وتذبذبها", "المسافات غير المنتظمة بين الكلمات", "خروج الحروف عن السطر والتشويه الخطي", "الضغط الزائد على القلم وإرهاق اليد"],
    description: "المقياس المعياري الذهبي المعتمد لتشخيص الديسغرافيا واضطراب التنسيق الحركي اليدوي أثناء الكتابة.",
    cutoff: "درجة الخطأ > 28 تدل على عسر كتابة دال (Dysgraphie) | سرعة أقل من -2 انحراف معياري",
    color: "from-rose-600 to-amber-600",
    icon: BookOpen
  },
  {
    id: "test-dys-dz",
    code: "TEST-DYS-DZ",
    title_ar: "رائز فحص صعوبات القراءة وعسر الكتابة والحساب باللهجة الجزائرية والفصحى",
    title_fr: "Batterie de Dépistage de la Dyslexie, Dysorthographie & Dyscalculie",
    category: "tdah_apprentissage",
    category_label: "صعوبات التعلم الأكاديمية",
    age_range: "6 - 12 سنة",
    duration: "30 دقيقة",
    source: "CREAPSY / معيار جزائري 🇩🇿",
    dimensions: ["الوعي الفونولوجي والتقطيع المقطعي", "سرعة القراءة ودقة الفهم القرائي", "الإملاء والتحليل الخطي للحروف المتشابهة", "المفاهيم الرياضية والعمليات العددية"],
    description: "روائز مقننة للكشف المبكر عن صعوبات التعلم الأكاديمية النوعية واقتراح خطة تربوية فردية (PEI) مكيفة للمدرسة.",
    cutoff: "فارق أداء يزيد عن سنتين دراسيتين مع ذكاء طبيعي يؤكد الصعوبة النوعية",
    color: "from-amber-600 to-orange-600",
    icon: BookOpen
  },
  {
    id: "wisc-5",
    code: "WISC-V",
    title_ar: "مقياس وكسلر لذكاء الأطفال والقدرات المعرفية العامة (WISC-V)",
    title_fr: "Wechsler Intelligence Scale for Children - 5th Edition (WISC-V)",
    category: "intelligence",
    category_label: "القدرات العقلية والذكاء",
    age_range: "6 سنوات إلى 16 سنة و 11 شهراً",
    duration: "60 - 90 دقيقة",
    source: "CREAPSY / Université 🇩🇿",
    dimensions: ["مؤشر الفهم اللفظي (VCI)", "مؤشر الاستدلال البصري المكاني (VSI)", "مؤشر الاستدلال المائع (FRI)", "مؤشر الذاكرة العاملة (WMI)", "مؤشر سرعة المعالجة (PSI)"],
    description: "البطارية النفسية الشاملة الأولى عالمياً لتحديد معامل الذكاء العام (FSIQ) وتشخيص الموهبة الفكرية وصعوبات التعلم وبطء التعلم.",
    cutoff: "< 70: قصور ذهني دال | 70-79: حدّي / بطء تعلم | 80-89: متوسط منخفض | 90-109: متوسط طبيعي | 110-119: فوق المتوسط | 120-129: متفوق | >= 130: موهبة عالية",
    color: "from-indigo-600 to-violet-800",
    icon: Zap
  },
  {
    id: "wais-4",
    code: "WAIS-IV",
    title_ar: "مقياس وكسلر لذكاء الراشدين والبالغين (WAIS-IV)",
    title_fr: "Wechsler Adult Intelligence Scale - 4th Edition (WAIS-IV)",
    category: "intelligence",
    category_label: "ذكاء وقدرات البالغين",
    age_range: "16 سنة إلى 79 سنة و 11 شهراً",
    duration: "75 - 90 دقيقة",
    source: "CREAPSY / Université 🇩🇿",
    dimensions: ["الفهم اللفظي واسترجاع المعلومات المجردة", "التنظيم الإدراكي وتركيب المكعبات والمصفوفات", "الذاكرة العاملة المتسلسلة للأرقام والحساب الذهني", "سرعة التمييز البصري والترميز الرمزي"],
    description: "الأداة المرجعية الكبرى لتقييم القدرات العقلية للبالغين وتحديد الكفاءات المهنية ومتابعة التدهور المعرفي في أمراض الأعصاب.",
    cutoff: "معامل الذكاء العام (QI Total) والمؤشرات الأربعة الكبرى",
    color: "from-indigo-800 to-blue-900",
    icon: Award
  },
  {
    id: "cpm",
    code: "CPM",
    title_ar: "مصفوفات رافن المتتابعة الملونة للذكاء غير اللفظي للأطفال (Raven CPM)",
    title_fr: "Progressive Matrices Couleurs de Raven (CPM)",
    category: "intelligence",
    category_label: "الذكاء غير اللفظي للأطفال",
    age_range: "5 - 11 سنة",
    duration: "20 - 30 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الاستدلال البصري التناظري", "إدراك العلاقات المكانية بين الأشكال", "إكمال النمط الهندسي الناقص", "القدرة التجريدية بدون لغة"],
    description: "الاختبار الأوسع تطبيقاً لقياس الذكاء الصافي متحرراً من العوائق اللغوية والثقافية، ومثالي لحالات الصم وتأخر النطق والتوحد.",
    cutoff: "مئين: < 5 عجز عقلي دال | 5-25 أقل من المتوسط | 25-75 متوسط طبيعي | 75-95 ذكاء مرتفع | > 95 عبقرية فكرية",
    color: "from-purple-600 to-pink-600",
    icon: Brain
  },
  {
    id: "spm",
    code: "SPM",
    title_ar: "مصفوفات رافن القياسية للذكاء العام والاستدلال المجرد (Raven SPM)",
    title_fr: "Progressive Matrices Standard de Raven (SPM)",
    category: "intelligence",
    category_label: "الذكاء العام والاستدلال المجرد",
    age_range: "11 سنة فما فوق (مراهقون وبالغون)",
    duration: "40 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الاستدلال الاستقرائي الصرف", "فهم القوانين الهندسية المعقدة", "القدرة على التفكير المنطقي التجريدي", "معامل g للذكاء العام (Spearman)"],
    description: "60 مصفوفة متدرجة الصعوبة لقياس الذكاء العام في التوجيه المدرسي والجامعي والتوظيف المهني.",
    cutoff: "مراتب تصنيف رافن الخمس (من الدرجة I العبقرية إلى الدرجة V القصور الذهني)",
    color: "from-indigo-600 to-teal-700",
    icon: Layers
  },
  {
    id: "apm",
    code: "APM",
    title_ar: "مصفوفات رافن المتتابعة المتقدمة للقدرات العقلية الفائقة (Raven APM)",
    title_fr: "Progressive Matrices Advanced de Raven (APM)",
    category: "intelligence",
    category_label: "الموهبة والتفوق العقلي",
    age_range: "مراهقون متفوقون وبالغون وطلاب الجامعات",
    duration: "40 - 60 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الاستدلال التجريدي فائق التعقيد", "القدرة على حل المشكلات غير النمطية", "التفكير الاستراتيجي المتقدم"],
    description: "مخصص للكشف عن الموهوبين والقدرات العقلية المتفوقة فوق المتوسط العادي لفرز النخب الفكرية والمهنية.",
    cutoff: "تمييز أصحاب النسبة المئوية العليا (Top 5% - 1%)",
    color: "from-violet-700 to-amber-600",
    icon: Sparkles
  },
  {
    id: "kohs",
    code: "KOHS",
    title_ar: "اختبار مكعبات كوهس للقدرة البصرية المكانية والذكاء العملي (Test des cubes de Kohs)",
    title_fr: "Test des cubes de Kohs",
    category: "intelligence",
    category_label: "الذكاء العملي والبصري المكاني",
    age_range: "6 سنوات فما فوق (أطفال وبالغون)",
    duration: "25 - 35 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["التحليل والتركيب البصري المكاني", "التنسيق الدقيق بين العين واليد", "سرعة إدراك التصاميم الملونة وإعادة بنائها بالمكعبات", "المرونة الإدراكية وتصحيح الأخطاء ذاتياً"],
    description: "أحد أعرق الاختبارات الأدائية غير اللفظية لقياس التفكير الهندسي والذكاء العملي وكشف اضطرابات الإدراك البصري المكاني.",
    cutoff: "حساب العمر العقلي الأدائي ومقارنته بالعمر الزمني",
    color: "from-teal-600 to-cyan-700",
    icon: Layers
  },
  {
    id: "col",
    code: "COL",
    title_ar: "مقياس كولومبيا للنضج العقلي والقدرة الاستدلالية (Échelle de maturité de Columbia)",
    title_fr: "Échelle de maturité mentale de Columbia (CMMS)",
    category: "intelligence",
    category_label: "المعرفة والنضج العقلي",
    age_range: "3.5 - 10 سنوات",
    duration: "15 - 20 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["التصنيف المفاهيمي للصور والأشكال", "إيجاد العنصر الدخيل أو المختلف", "التمييز الإدراكي بين الخصائص (الحجم، اللون، الشكل، الاستخدام)"],
    description: "لا يتطلب أي استجابة لفظية أو حركية معقدة (يكفي الإشارة باليد أو بالعين)، ومثالي للأطفال المصابين بالشلل الدماغي (IMC) والحبسة.",
    cutoff: "حساب معامل النضج العقلي (Index de maturité) والعمر المكافئ",
    color: "from-emerald-600 to-blue-600",
    icon: Smile
  },
  {
    id: "nemi-2",
    code: "NEMI-2",
    title_ar: "المقياس المتري الحديث للذكاء للأطفال (NEMI-2 - Cognet)",
    title_fr: "Nouvelle échelle métrique de l'intelligence (NEMI-2)",
    category: "intelligence",
    category_label: "القدرات العقلية للأطفال",
    age_range: "4.5 - 12.5 سنة",
    duration: "45 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["المعرفة اللفظية والتسمية", "الاستدلال المباشر والتناظرات", "الذاكرة الفورية للأرقام والجمل", "التكيف البصري المكاني"],
    description: "البديل الفرنسي الأسرع والأكثر تكيفاً عيادياً لمقاييس وكسلر في تقييم الذكاء الشامل للأطفال.",
    cutoff: "معامل الكفاءة العامة (Indice d'efficience) وتحديد الفئة النمائية",
    color: "from-indigo-600 to-cyan-700",
    icon: Brain
  },
  {
    id: "b101",
    code: "B101",
    title_ar: "اختبار الذكاء العملي الحسي لبونارديل (Test B101 de Bonnardel)",
    title_fr: "Test d'intelligence concrète de Bonnardel (B101)",
    category: "intelligence",
    category_label: "الذكاء العملي الملموس",
    age_range: "مراهقون وبالغون",
    duration: "20 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الذكاء التقني والميكانيكي", "حل المشكلات الملموسة", "الاستبصار الحركي الفضائي"],
    description: "رائز أدائي كلاسيكي لقياس الذكاء العملي للأفراد ذوي التعليم البسيط أو في التوجيه للتكوين المهني والتقني.",
    cutoff: "توزيع معياري للقدرات الحركية الفكرية",
    color: "from-amber-600 to-teal-700",
    icon: Zap
  },
  {
    id: "baf",
    code: "BAF",
    title_ar: "بطارية الاستعدادات والقدرات الأساسية للتوجيه (BAF)",
    title_fr: "Batterie d'aptitudes fondamentales (BAF)",
    category: "intelligence",
    category_label: "الاستعدادات والقدرات",
    age_range: "مراهقون وبالغون",
    duration: "45 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["القدرة اللفظية", "القدرة العددية", "القدرة المكانية", "سرعة الإدراك والتركيز"],
    description: "تستخدم على نطاق واسع في التوجيه المدرسي والمهني في الجزائر لتحديد الميول والقدرات المعرفية الأساسية.",
    cutoff: "بروفيل الاستعدادات النسبية (Profile d'aptitudes)",
    color: "from-blue-700 to-indigo-800",
    icon: Award
  },
  {
    id: "bat-adul",
    code: "BAT-ADUL",
    title_ar: "بطارية تقييم ذكاء وقدرات الراشدين (BAT-ADUL)",
    title_fr: "Batterie d'évaluation de l'intelligence de l'adulte",
    category: "intelligence",
    category_label: "الذكاء المعرفي للراشدين",
    age_range: "بالغون",
    duration: "50 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الاستدلال المنطقي اللفظي وغير اللفظي", "الذاكرة المعرفية", "حل المعضلات العقلية"],
    description: "بطارية مخصصة لقياس معامل الذكاء لدى البالغين وتحديد كفاءات التفكير التحليلي.",
    cutoff: "معيار كمي للذكاء",
    color: "from-slate-700 to-indigo-800",
    icon: Brain
  },
  {
    id: "bat-enf-ado",
    code: "BAT-ENF-ADO",
    title_ar: "بطارية تقييم ذكاء الأطفال والمراهقين (BAT-ENF-ADO)",
    title_fr: "Batterie d'évaluation de l'intelligence enfant et adolescent",
    category: "intelligence",
    category_label: "الذكاء النمائي",
    age_range: "أطفال ومراهقون (6 - 16 سنة)",
    duration: "45 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الاستيعاب المفاهيمي", "الطلاقة الفكرية", "القدرة الحسابية والمنطقية"],
    description: "فحص عيادي لتقدير مستوى الذكاء وتحديد الاحتياجات التربوية الخاصة في الوسط المدرسي الجزائري.",
    cutoff: "درجة معيارية حسب الفئة العمرية",
    color: "from-cyan-700 to-blue-800",
    icon: Zap
  },
  {
    id: "edei-r",
    code: "EDEI-R",
    title_ar: "المقاييس الفارقة للكفاءة الفكرية المعدلة (EDEI-R - Perron-Borelli)",
    title_fr: "Échelles différentielles d'efficience intellectuelle révisées",
    category: "intelligence",
    category_label: "الكفاءة الفكرية الفارقة",
    age_range: "3 - 11 سنة",
    duration: "45 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["المعرفة اللفظية واستعمال المفردات", "التصنيف الصوري والمنطق", "التنظيم البصري الحركي", "الذاكرة المكانية"],
    description: "بطارية نفسية ممتازة لدراسة التباين في البنية المعرفية للطفل وتحديد ما إذا كان الذكاء متوازناً أو متبايناً بشدة.",
    cutoff: "حساب حاصل الذكاء اللفظي وغير اللفظي والعام",
    color: "from-purple-600 to-teal-700",
    icon: Scale
  },
  {
    id: "nnat",
    code: "NNAT",
    title_ar: "اختبار ناجليري للقدرة غير اللفظية على التفكير (NNAT)",
    title_fr: "Naglieri Nonverbal Ability Test (NNAT)",
    category: "intelligence",
    category_label: "القدرة الاستدلالية غير اللفظية",
    age_range: "5 - 17 سنة",
    duration: "30 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["إكمال الأنماط الهندسية", "الاستدلال الاستدلالي التناظري", "التفكير في الفضاء والحركة المكانية"],
    description: "مقياس عادل وموضوعي للغاية للأطفال من مختلف الخلفيات اللغوية والاجتماعية لقياس القدرة الاستدلالية الخالصة.",
    cutoff: "مئين القدرة غير اللفظية",
    color: "from-teal-600 to-indigo-700",
    icon: Sparkles
  },
  {
    id: "d2000",
    code: "D2000",
    title_ar: "رائز التفكير الاستدلالي السريع للبالغين (Test D2000)",
    title_fr: "Test de raisonnement général D2000",
    category: "intelligence",
    category_label: "الاستدلال المنطقي",
    age_range: "بالغون",
    duration: "30 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["المنطق الرقمي والاستقرائي", "اكتشاف القواعد الرياضية المتسلسلة", "السرعة المعرفية في حل المشكلات"],
    description: "اختبار حديث لتقييم الكفاءة الاستدلالية العامة في التوظيف والتقييم الإكلينيكي المعرفي.",
    cutoff: "معيار تدرج القدرات المنطقية",
    color: "from-indigo-700 to-purple-800",
    icon: Zap
  },
  {
    id: "dat-5",
    code: "DAT-5",
    title_ar: "اختبارات الاستعدادات التفاضلية المتعددة (DAT-5)",
    title_fr: "Differential Aptitude Tests - 5th Edition (DAT-5)",
    category: "intelligence",
    category_label: "الاستعدادات والقدرات التفاضلية",
    age_range: "مراهقون وبالغون (12 سنة فما فوق)",
    duration: "60 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الاستدلال اللفظي واللغوي", "الاستدلال العددي والرياضي", "الاستدلال الميكانيكي والفيزيائي", "العلاقات المكانية والفراغية", "السرعة والدقة الكتابية"],
    description: "البطارية العالمية لتشخيص الكفاءات الخاصة وتوجيه الطلاب نحو التخصصات العلمية أو الأدبية أو التقنية بدقة متناهية.",
    cutoff: "بروفيل القدرات التفاضلية المئيني",
    color: "from-blue-600 to-amber-600",
    icon: Award
  },
  {
    id: "evac",
    code: "EVAC",
    title_ar: "الاختبار اللفظي للقدرات المعرفية والتفكير المجرد (EVAC)",
    title_fr: "Épreuve verbale d'aptitudes cognitives (EVAC)",
    category: "intelligence",
    category_label: "القدرات اللفظية والمعرفية",
    age_range: "مراهقون وبالغون",
    duration: "25 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الاستدلال اللفظي التجريدي", "فهم التناظرات اللغوية المعقدة", "الثراء المفاهيمي والمعجمي"],
    description: "يقيس الذكاء المتبلور (Intelligence Cristallisée) والقدرة على استخدام اللغة كأداة للتفكير والاستنتاج المنطقي.",
    cutoff: "درجة معيارية للذكاء اللفظي",
    color: "from-cyan-600 to-indigo-800",
    icon: MessageSquare
  },
  {
    id: "intso",
    code: "INTSO",
    title_ar: "اختبار الذكاء الاجتماعي وفهم المواقف الإنسانية (INTSO)",
    title_fr: "Test d'intelligence sociale (INTSO)",
    category: "intelligence",
    category_label: "الذكاء الاجتماعي والتواصلي",
    age_range: "بالغون",
    duration: "30 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["إدراك النوايا والمشاعر من ملامح الوجه", "فهم السياقات والمواقف الاجتماعية المعقدة", "اللباقة وحل النزاعات بين الأفراد", "المرونة السلوكية الاجتماعية"],
    description: "يقيس كفاءة الفرد في قراءة الآخرين والتصرف بحكمة في العلاقات الإنسانية وبيئات العمل والقيادة.",
    cutoff: "مؤشر الذكاء الاجتماعي: منخفض / متوسط / مرتفع كفاءة",
    color: "from-emerald-600 to-teal-700",
    icon: Users
  },
  {
    id: "rais2000",
    code: "RAIS2000",
    title_ar: "رائز التفكير والاستدلال المتقدم للراشدين (RAIS 2000)",
    title_fr: "Test de raisonnement avancé RAIS 2000",
    category: "intelligence",
    category_label: "الاستدلال المتقدم",
    age_range: "بالغون",
    duration: "35 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["المنطق المجرد المتعدد المتغيرات", "اكتشاف العلاقات الخفية بين الرموز", "التفكير الاستراتيجي تحت الضغط"],
    description: "رائز استدلالي مكثف لقياس سقف القدرات المنطقية والتجريدية لدى البالغين.",
    cutoff: "معيار استدلالي مقنن",
    color: "from-indigo-600 to-purple-800",
    icon: Zap
  },
  {
    id: "becs",
    code: "BECS",
    title_ar: "بطارية التقييم المعرفي والوجداني الاجتماعي للطفل (BECS - Adrien)",
    title_fr: "Batterie d'évaluation cognitive et socio-émotionnelle",
    category: "intelligence",
    category_label: "النمو المعرفي والوجداني",
    age_range: "الرضع والأطفال الصغار (4 أشهر إلى 4 سنوات)",
    duration: "40 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الدوام الموضوعي للشيء (Permanence de l'objet)", "العلاقات السببية والوسائل والغايات", "التقليد الحركي والصوتي", "التنظيم الانفعالي والمشاركة الوجدانية"],
    description: "أداة فرنسية جزائرية مقننة مبنية على نظرية بياجيه لتقييم النمو المعرفي والانفعالي في اضطرابات النمو الشاملة والتوحد.",
    cutoff: "تحديد العمر النمائي في 16 مجالاً معرفياً ووجدانياً",
    color: "from-pink-600 to-indigo-700",
    icon: HeartPulse
  },
  {
    id: "bdi-2",
    code: "BDI-II",
    title_ar: "مقياس بيك للاكتئاب السريري - الإصدار الثاني (Beck Depression Inventory)",
    title_fr: "Inventaire de dépression de Beck II (BDI-II)",
    category: "psychologie",
    category_label: "الاكتئاب والاضطرابات المزاجية",
    age_range: "13 سنة فما فوق (مراهقون وبالغون)",
    duration: "10 - 15 دقيقة",
    source: "CREAPSY / معيار مقنن 🇩🇿",
    dimensions: ["الحزن واليأس وفقدان الأمل في المستقبل", "فقدان المتعة والاهتمام (Anhedonia)", "مشاعر الذنب ولوم الذات والأفكار الانتحارية", "الأعراض الجسدية (النوم، الشهية، الإرهاق، الرغبة)"],
    description: "المقياس الذاتي الأشهر عالمياً لتشخيص وتقييم شدة الاكتئاب وتحديد خطورة الأفكار الانتحارية بدقة سريرية متناهية.",
    cutoff: "0 - 13: اكتئاب في حده الأدنى (طبيعي) | 14 - 19: اكتئاب خفيف | 20 - 28: اكتئاب متوسط | 29 - 63: اكتئاب شديد حاد",
    color: "from-purple-700 to-indigo-900",
    icon: Frown
  },
  {
    id: "mdi-c",
    code: "MDI-C",
    title_ar: "مقياس الاكتئاب السريري متعدد الأبعاد للأطفال (MDI-C - Berndt)",
    title_fr: "Inventaire de dépression pour enfants (MDI-C)",
    category: "psychologie",
    category_label: "اكتئاب الأطفال والمراهقين",
    age_range: "7 - 17 سنة",
    duration: "15 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["تقدير الذات السلبي ومشاعر الفشل", "القلق والانزعاج الانفعالي", "الانسحاب الاجتماعي والتباعد عن الأصدقاء", "الشعور بالعجز والتشاؤم", "الأعراض الجسدية والوهن"],
    description: "استبيان نفسي مخصص للأطفال والمراهقين لرصد الاكتئاب المقنع الذي قد يظهر في شكل عناد أو تراجع مدرسي مفاجئ.",
    cutoff: "درجة تائية T-Score >= 65 تشير إلى اكتئاب سريري دال عند الطفل",
    color: "from-rose-600 to-indigo-800",
    icon: Frown
  },
  {
    id: "r-cmas",
    code: "R-CMAS",
    title_ar: "مقياس مظاهر القلق الصريح والمعدل للأطفال والمراهقين (R-CMAS - Reynolds)",
    title_fr: "Revised Children's Manifest Anxiety Scale (R-CMAS)",
    category: "psychologie",
    category_label: "القلق والتوتر لدى الأطفال",
    age_range: "6 - 19 سنة",
    duration: "15 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["القلق الفسيولوجي (تسارع النبض، المغص، التعرق)", "القلق والوساوس والانشغال المفرط بالامتحانات", "المخاوف الاجتماعية والتردد", "مقياس الكذب والرغبة في تجميل الصورة"],
    description: "أداة سريرية قياسية لتشخيص اضطرابات القلق المدرسي والقلق المعمم ونوبات الهلع عند التلاميذ.",
    cutoff: "درجة T > 60: قلق دال | مقياس الكذب > 60: نتائج متحفظة",
    color: "from-amber-600 to-rose-700",
    icon: Activity
  },
  {
    id: "stai-y",
    code: "STAI-Y",
    title_ar: "مقياس سبيلبرجر لقلق السمة وقلق الحالة للبالغين (STAI-Y - Spielberger)",
    title_fr: "Inventaire d'anxiété état-trait de Spielberger (STAI-Y)",
    category: "psychologie",
    category_label: "القلق العام والسمات الانفعالية",
    age_range: "مراهقون وبالغون (14 سنة فما فوق)",
    duration: "15 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["قلق الحالة (Anxiété-État): التوتر اللحظي في موقف معين كالامتحان أو العملية", "قلق السمة (Anxiété-Trait): الميل الثابت والمزمن لدى الشخصية للشعور بالخوف والتهديد"],
    description: "الأداة المرجعية الأولى عالمياً للتفريق بين القلق العابر المؤقت والقلق البنيوي المتجذر في تكوين الشخصية.",
    cutoff: "< 35: قلق منخفض جداً | 36-45: قلق منخفض | 46-55: قلق متوسط | 56-65: قلق مرتفع | > 65: قلق شديد جداً وحاد",
    color: "from-amber-500 to-orange-700",
    icon: Activity
  },
  {
    id: "ciss",
    code: "CISS",
    title_ar: "مقياس استراتيجيات التكيف والتعامل مع الضغوط النفسية (CISS - Endler)",
    title_fr: "Coping Inventory for Stressful Situations (CISS)",
    category: "psychologie",
    category_label: "التكيف والتعامل مع الضغوط",
    age_range: "مراهقون وبالغون",
    duration: "15 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["استراتيجية التعامل المرتكز على حل المشكلة (Task-oriented)", "استراتيجية التعامل المرتكز على الانفعال والتفريغ العاطفي (Emotion-oriented)", "استراتيجية التجنب والهروب والإلهاء (Avoidance-oriented)"],
    description: "يحدد الآليات النفسية التي يعتمدها الشخص عند مواجهة الأزمات، ويساعد في توجيه العلاج النفسي المعرفي والسلوكي.",
    cutoff: "تحديد نمط التكيف السائد ومدى فاعليته النفسية",
    color: "from-teal-600 to-indigo-800",
    icon: ShieldAlert
  },
  {
    id: "str",
    code: "STR",
    title_ar: "مقياس الإجهاد والضغط النفسي والاحتراق (Test de Stress / Burnout)",
    title_fr: "Échelle d'évaluation du stress perçu et vulnérabilité",
    category: "psychologie",
    category_label: "الضغط النفسي والإجهاد",
    age_range: "بالغون",
    duration: "10 دقائق",
    source: "CREAPSY 🇩🇿",
    dimensions: ["مستوى الضغط المتصور في الحياة اليومية", "الاستجابات الجسدية للإجهاد (صداع، أرق، توتر عضلي)", "الشعور بفقدان السيطرة على الأحداث"],
    description: "يقيس مستوى الحمل النفسي الزائد وقابلية الفرد للإصابة بمتلازمة الاحتراق النفسي والمهني (Burnout).",
    cutoff: "ضغط طبيعي / ضغط مرتفع يحتاج استرخاء / إجهاد مزمن حرج",
    color: "from-rose-600 to-amber-700",
    icon: Activity
  },
  {
    id: "traumaq",
    code: "TRAUMAQ",
    title_ar: "استبيان الصدمات النفسية واضطراب كرب ما بعد الصدمة (TRAUMAQ)",
    title_fr: "Questionnaire d'évaluation du traumatisme psychologique",
    category: "psychologie",
    category_label: "الصدمات النفسية و PTSD",
    age_range: "مراهقون وبالغون",
    duration: "20 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["معايشات الاسترجاع المؤلم والذكريات الاقتحامية (Flashbacks)", "سلوكيات التجنب للأماكن والمحفزات الصادمة", "الخدر الانفعالي وتغير المزاج المعرفي", "الاستثارة الفسيولوجية المفرطة وسرعة الفزع"],
    description: "فحص سريري للأحداث الصادمة (حوادث، فقدان مفاجئ، كوارث) وتحديد مؤشر اضطراب كرب ما بعد الصدمة.",
    cutoff: "تأكيد وجود مؤشرات سريرية لاضطراب ما بعد الصدمة تستلزم علاج EMDR أو CBT",
    color: "from-red-600 to-slate-900",
    icon: ShieldAlert
  },
  {
    id: "sei",
    code: "SEI",
    title_ar: "مقياس كوبرسميث لتقدير الذات واحترام النفس (SEI - Coopersmith)",
    title_fr: "Inventaire d'estime de soi de Coopersmith (SEI)",
    category: "psychologie",
    category_label: "تقدير الذات والصورة النفسية",
    age_range: "أطفال، مراهقون، وبالغون (9 سنوات فما فوق)",
    duration: "15 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["تقدير الذات العام والشخصي", "تقدير الذات في الوسط الأسري والعائلي", "تقدير الذات الاجتماعي وبين الأقران", "تقدير الذات في المدرسة أو العمل"],
    description: "أداة قياسية لتقييم ثقة الفرد بنفسه ومشاعره تجاه كفاءته الشخصية وقيمته الذاتية في الحياة.",
    cutoff: "تقدير ذات منخفض (أقل من المئين 25) / متوسط طبيعي / مرتفع وناضج",
    color: "from-emerald-500 to-teal-700",
    icon: Smile
  },
  {
    id: "psa",
    code: "PSA",
    title_ar: "بروفيل التكيف الاجتماعي والوجداني للطفل (Profil Socio-Affectif - PSA)",
    title_fr: "Profil socio-affectif de l'enfant (PSA - LaFreniere)",
    category: "psychologie",
    category_label: "التكيف الاجتماعي والانفعالي",
    age_range: "2.5 - 6 سنوات",
    duration: "20 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الكفاءة الاجتماعية والتعاون", "الغضب والعدوانية نحو الأقران", "القلق والانطواء والانعزال في الروضة"],
    description: "يقيم نضج التفاعلات الوجدانية والسلوكية للطفل في بيئة الروضة أو الحضانة مع المعلمات والأقران.",
    cutoff: "بروفيل تكيف وجداني سليم / مشكلات سلوكية ظاهرة",
    color: "from-teal-600 to-indigo-700",
    icon: Users
  },
  {
    id: "tsea",
    code: "TSEA",
    title_ar: "المقياس النفسي الاجتماعي والتربوي للبيئة الأسرية (TSEA)",
    title_fr: "Test et échelle socio-éducative",
    category: "psychologie",
    category_label: "الوسط النفسي والتربوي",
    age_range: "أطفال ومراهقون",
    duration: "25 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["المناخ الأسري والتواصل الوالدي", "أنماط المعاملة الوالدية (تسلط، تساهل، اتزان)", "الاستقرار السيكولوجي الأسري"],
    description: "رصد العوامل النفسية الاجتماعية والبيئية المؤثرة على التكيف النفسي للطفل والمراهق.",
    cutoff: "مؤشر دعم أسري إيجابي مقابل بيئة ضاغطة",
    color: "from-blue-600 to-purple-700",
    icon: User
  },
  {
    id: "mmpi-2",
    code: "MMPI-2",
    title_ar: "استبيان مينيسوتا متعدد الأوجه للشخصية - الإصدار الثاني للبالغين (MMPI-2)",
    title_fr: "Minnesota Multiphasic Personality Inventory-2 (MMPI-2)",
    category: "psychologie",
    category_label: "الشخصية والتشخيص الإكلينيكي",
    age_range: "البالغون (18 سنة فما فوق)",
    duration: "60 - 90 دقيقة",
    source: "CREAPSY / الجامعات 🇩🇿",
    dimensions: ["المقاييس الإكلينيكية العشرة (الهستيريا، الاكتئاب، الفصام، الهوس، البارانويا...)", "مقاييس الصدق والتحقق (L, F, K)", "مقاييس الشخصية والميول السلوكية"],
    description: "أضخم وأعرق استبيان إكلينيكي في تاريخ علم النفس لتشخيص اضطرابات الشخصية والأمراض النفسية والطب الشرعي.",
    cutoff: "درجة تائية T-Score > 65 تعتبر دالة إكلينيكياً في المقاييس الإكلينيكية",
    color: "from-slate-800 to-indigo-950",
    icon: Award
  },
  {
    id: "mmpi-a",
    code: "MMPI-A",
    title_ar: "استبيان مينيسوتا للشخصية للمراهقين (MMPI-A)",
    title_fr: "Minnesota Multiphasic Personality Inventory - Adolescent (MMPI-A)",
    category: "psychologie",
    category_label: "شخصية المراهق والاضطرابات",
    age_range: "14 - 18 سنة",
    duration: "45 - 60 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الهوية والاغتراب النفسي في المراهقة", "مشكلات السلوك والتمرد الأسري والمدرسي", "القلق والمزاج الاكتئابي والانفعالي", "مقاييس الصدق المتخصصة للمراهقين"],
    description: "نسخة مكيفة للمراهقين لرصد الأزمات السيكولوجية وسلوكيات المخاطرة والانحراف وبناء الهوية.",
    cutoff: "T-Score > 65 يدل على معاناة نفسية دالة",
    color: "from-purple-700 to-rose-800",
    icon: Activity
  },
  {
    id: "neo-pi-r",
    code: "NEO-PI-R",
    title_ar: "قائمة العوامل الخمسة الكبرى للشخصية (NEO-PI-R - Costa & McCrae)",
    title_fr: "Inventaire de personnalité NEO PI-R (Big Five)",
    category: "psychologie",
    category_label: "العوامل الكبرى للشخصية (Big 5)",
    age_range: "البالغون والمراهقون (17 سنة فما فوق)",
    duration: "30 - 45 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["العصابية والهشاشة الانفعالية (Neuroticism)", "الانبساطية والاجتماعية (Extraversion)", "الانفتاح على الخبرات والابتكار (Openness)", "المقبولية والطيبة في التعامل (Agreeableness)", "يقظة الضمير والمسؤولية والالتزام (Conscientiousness)"],
    description: "النموذج العلمي الأحدث والأكثر موثوقية لوصف الأبعاد الطبيعية للشخصية الإنسانية في الإرشاد النفسي والتوجيه المهني.",
    cutoff: "بروفيل خماسي الأبعاد يحدد السمات النفسية الأساسية بدقة إحصائية",
    color: "from-indigo-600 to-teal-600",
    icon: Layers
  },
  {
    id: "gpp-i",
    code: "GPP-I",
    title_ar: "استبيان جوردون لمظهر وبروفيل الشخصية (GPP-I - Gordon)",
    title_fr: "Inventaire de personnalité de Gordon (GPP-I)",
    category: "psychologie",
    category_label: "سمات الشخصية والقيادة",
    age_range: "مراهقون وبالغون",
    duration: "20 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["السيطرة والقيادية", "المسؤولية الذاتية", "الاتزان الانفعالي", "المؤانسة والعلاقات العامة"],
    description: "يستخدم بكثرة في اختيار الكفاءات والإرشاد المهني والنفسي لتقييم الشخصية العملية.",
    cutoff: "توزيع رتبي للسمات القيادية والانفعالية",
    color: "from-blue-600 to-indigo-800",
    icon: User
  },
  {
    id: "pnp",
    code: "PNP",
    title_ar: "استبيان بروفيل الشخصية السريرية والتكيف النفسي (PNP - Pichot)",
    title_fr: "Profil de personnalité de Pichot (PNP)",
    category: "psychologie",
    category_label: "التكيف والهشاشة النفسية",
    age_range: "بالغون",
    duration: "25 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الميل العصابي", "الاستجابات الهستيرية والجسدنة", "الميل للاضطراب المزاجي", "مستوى التكيف الواقعي"],
    description: "أداة سريعة لفرز الأعراض العصابية والشخصية الهشة في الفحص العيادي الأولي.",
    cutoff: "مؤشر الهشاشة العصابية",
    color: "from-slate-700 to-rose-800",
    icon: ShieldAlert
  },
  {
    id: "siv-spv",
    code: "SIV-SPV",
    title_ar: "استبيان القيم الشخصية والتفاعلية في العلاقات (SIV / SPV - Gordon)",
    title_fr: "Inventaire des valeurs personnelles et interpersonnelles",
    category: "psychologie",
    category_label: "المنظومة القيمية والمبادئ",
    age_range: "مراهقون وبالغون",
    duration: "25 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["قيمة الاستقلالية والحرية الفردية", "قيمة التوافق الاجتماعي والمساعدة", "قيمة الاعتراف والتقدير المجتمعي", "قيمة القيادة والتأثير"],
    description: "يساعد الأخصائي النفسي في فهم المنظومة الأخلاقية والقيمية المحركة لدوافع المريض في اتخاذ القرارات المصيرية.",
    cutoff: "ترتيب الأولويات القيمية للشخصية",
    color: "from-amber-600 to-emerald-700",
    icon: Award
  },
  {
    id: "rip",
    code: "RIP",
    title_ar: "استبيان رصد الميول والاهتمامات المهنية (Relevé des intérêts professionnels)",
    title_fr: "Relevé des intérêts professionnels (RIP)",
    category: "psychologie",
    category_label: "الميول والتوجيه المهني",
    age_range: "مراهقون وبالغون",
    duration: "30 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الاهتمام بالمهن العلمية والتقنية", "الاهتمام بالمجالات الأدبية والفنية", "الاهتمام بالأنشطة التجارية والتسيير", "الاهتمام بالخدمات الاجتماعية والمساعدة الإنسانية"],
    description: "أداة توجيه مدرسي وجامعي تساعد في اختيار الشعبة والمسار المهني الملائم للشخصية.",
    cutoff: "مؤشر التوافق بين الميول والشعب المتاحة",
    color: "from-teal-600 to-blue-700",
    icon: Compass
  },
  {
    id: "rorschach",
    code: "RORSCHACH",
    title_ar: "اختبار رورشاخ لبقع الحبر والتشخيص الإسقاطي للشخصية (Rorschach)",
    title_fr: "Psychodiagnostic de Rorschach (Épreuve des taches d'encre)",
    category: "psychologie",
    category_label: "الاختبارات الإسقاطية المعمقة",
    age_range: "مراهقون وبالغون (وكذلك الأطفال فوق 7 سنوات)",
    duration: "45 - 60 دقيقة + التحليل السيكودينامي",
    source: "CREAPSY / المستشفيات والجامعات 🇩🇿",
    dimensions: ["نمط الإدراك والمحددات (الشكل، اللون، الحركة F, C, K)", "محتوى الاستجابات ودلالاتها الرمزية", "مستوى التماسك المنطقي واستبصار الواقع (F+%)", "آليات الدفاع والصراعات اللاشعورية"],
    description: "قمة الاختبارات الإسقاطية السريرية لفهم البنية العميقة للشخصية، التمييز بين الذهان والعصاب، وتشخيص الهشاشة النفسية.",
    cutoff: "تحليل شامل لبروفيل المحددات السيكوغرامية (Psychogramme)",
    color: "from-slate-900 via-purple-950 to-slate-900",
    icon: Eye
  },
  {
    id: "tat",
    code: "TAT",
    title_ar: "اختبار تفهم الموضوع الإسقاطي للراشدين (TAT - Murray)",
    title_fr: "Thematic Apperception Test (TAT)",
    category: "psychologie",
    category_label: "الاختبارات الإسقاطية للبالغين",
    age_range: "مراهقون وبالغون (14 سنة فما فوق)",
    duration: "45 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["البطل والتطابق النفسي مع الشخصية الرئيسية", "الحاجات والدوافع اللاشعورية العميقة", "الضغوط البيئية المدركة من المحيط", "النهايات وحل الصراعات النفسية"],
    description: "31 لوحة لمواقف إنسانية غامضة يسقط عليها المفحوص مشاعره وصراعاته وعلاقاته بالموضوع والأم والأب والسلطة.",
    cutoff: "تحليل سيكودينامي عيادي للعقد النفسية والآليات الدفاعية",
    color: "from-purple-800 to-indigo-900",
    icon: BookOpen
  },
  {
    id: "cat",
    code: "CAT",
    title_ar: "اختبار تفهم الموضوع الإسقاطي للأطفال (CAT - Bellak)",
    title_fr: "Children's Apperception Test (CAT)",
    category: "psychologie",
    category_label: "إسقاطي للأطفال",
    age_range: "3 - 10 سنوات",
    duration: "30 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الصراع الأوديبي والعلاقة مع الوالدين", "الغيرة الأخوية والتنافس بين الإخوة", "المخاوف والعدوانية والقلق الفمي والشرجي", "الخوف من العقاب والتخلي"],
    description: "10 لوحات لحيوانات في مواقف إنسانية تحفز خيال الطفل للتعبير عن مخاوفه وصراعاته الداخلية دون خوف من اللوم.",
    cutoff: "تحليل إكلينيكي لدينامية الطفل في الأسرة",
    color: "from-pink-600 to-rose-700",
    icon: Smile
  },
  {
    id: "fat",
    code: "FAT",
    title_ar: "اختبار تفهم الأسرة الإسقاطي (Family Apperception Test - FAT)",
    title_fr: "Family Apperception Test (FAT)",
    category: "psychologie",
    category_label: "إسقاطي للعلاقات الأسرية",
    age_range: "أطفال ومراهقون (6 - 15 سنة)",
    duration: "30 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["إدراك الروابط والتلاحم الأسري", "التواصل والصراعات بين الوالدين", "مكانة الطفل وموقعه في النسق العائلي", "مشاعر الإهمال أو الحماية المفرطة"],
    description: "لوحات مخصصة لتشخيص ديناميات الأسرة وكشف النزاعات الأسرية الصامتة المؤثرة على الطفل.",
    cutoff: "تحليل نسقي عيادي للروابط الأسرية",
    color: "from-indigo-600 to-teal-700",
    icon: Users
  },
  {
    id: "ftt",
    code: "FTT",
    title_ar: "اختبار حكايات الجنيات والقصص الرمزية للأطفال (Fairy Tale Test - FTT)",
    title_fr: "Fairy Tale Test (FTT)",
    category: "psychologie",
    category_label: "إسقاطي رمزي للأطفال",
    age_range: "6 - 12 سنة",
    duration: "35 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["العدوانية والشعور بالظلم", "الحاجة للحماية والحنان", "الشعور بالقوة مقابل الضعف والعجز", "التعاطف مع الشخصيات المظلومة"],
    description: "يستخدم شخصيات الحكايات الشعبية المشهورة (ليلى والذئب، بياض الثلج، الغول) لسبر أغوار المشاعر المكبوتة للطفل.",
    cutoff: "تحليل إسقاطي للشخصية النامية",
    color: "from-amber-500 to-purple-600",
    icon: Sparkles
  },
  {
    id: "patte-noire",
    code: "PN",
    title_ar: "اختبار الساق السوداء الإسقاطي للأطفال (Test de la Patte Noire - Corman)",
    title_fr: "Test de la Patte Noire (Corman)",
    category: "psychologie",
    category_label: "التحليل النفسي للأطفال",
    age_range: "4 - 12 سنة",
    duration: "30 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الصراع الفمي والمرحلة الشرجية", "الصدمة الأوديبية والغيرة من الأخ الصغير", "مشاعر الذنب والرغبة في العقاب", "التطابق مع الأب أو الأم"],
    description: "المغامرات المصورة للخنزير الصغير ذي الساق السوداء، وهو أداة إكلينيكية مفضلة في العيادات النفسية للأطفال في الجزائر.",
    cutoff: "تحديد العقدة النفسية الأساسية المحركة للأعراض السلوكية والتبول اللاإرادي",
    color: "from-purple-600 to-indigo-800",
    icon: Smile
  },
  {
    id: "dessin-famille",
    code: "FAM",
    title_ar: "اختبار رسم الأسرة الإسقاطي (Test du dessin de la famille - Corman)",
    title_fr: "Test du dessin de la famille (Corman)",
    category: "psychologie",
    category_label: "إسقاطي بالرسم للأطفال",
    age_range: "5 - 14 سنة",
    duration: "20 دقيقة",
    source: "CREAPSY / Base comp 🇩🇿",
    dimensions: ["موقع الطفل وترتيب رسم أفراد الأسرة", "حجم الشخصيات ومسافات التباعد أو التقارب", "إهمال أو حذف أحد أفراد الأسرة", "التطابق اللاشعوري والمكانة التفضيلية"],
    description: "من أسهل وأقوى الاختبارات الإسقاطية للكشف عن الصراعات الأسرية وإحساس الطفل بمكانته داخل بيته.",
    cutoff: "تحليل رمزي دلالي لخطوط ومكونات الرسم والتعليق اللفظي المصاحب",
    color: "from-emerald-600 to-teal-700",
    icon: Users
  },
  {
    id: "dessin-arbre",
    code: "TDA-2",
    title_ar: "اختبار رسم الشجرة لإسقاط الشخصية والتطور النفسي (Test de l'arbre - Koch)",
    title_fr: "Test du dessin de l'arbre (Koch / Stora)",
    category: "psychologie",
    category_label: "إسقاطي بالرسم",
    age_range: "كافة الأعمار (أطفال، مراهقون، وبالغون)",
    duration: "15 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الجذور والأرض: الاستقرار النفسي والتجذر الغريزي", "الجذع: قوة الأنا والصلابة الانفعالية ومقاومة الصدمات", "الفروع والأغصان: التواصل مع المحيط الخارجي والطموح", "الندوب والكسور: علامات الصدمات النفسية القديمة"],
    description: "رسم شجرة على ورقة بيضاء، أداة إسقاطية بصرية فائقة البساطة تعكس عمق التاريخ النفسي والجروح العاطفية للشخصية.",
    cutoff: "تحليل بنيوي سيكودينامي",
    color: "from-emerald-700 to-amber-700",
    icon: Award
  },
  {
    id: "dessin-maison",
    code: "TDM",
    title_ar: "اختبار رسم البيت الإسقاطي (Test du dessin de la maison)",
    title_fr: "Test du dessin de la maison",
    category: "psychologie",
    category_label: "إسقاطي بالأشكال",
    age_range: "أطفال ومراهقون",
    duration: "15 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الأبواب والنوافذ: الانفتاح والتواصل مع المجتمع أو الانغلاق", "السقف والمدخنة: التفكير التخيلي والدفء العاطفي", "الأسوار والتحصينات: الحذر والوسواس أو الشعور بالخطر"],
    description: "يمثل البيت رمزياً الذات والجسد والأمن العاطفي الداخلي والبيئة الحاضنة للطفل.",
    cutoff: "تحليل مؤشرات الأمن النفسي مقابل الخوف والقلق",
    color: "from-amber-600 to-orange-700",
    icon: User
  },
  {
    id: "goodenough",
    code: "GOODENOUGH",
    title_ar: "اختبار رسم الرجل لجودايناف لتقييم النضج العقلي والنفسي (Goodenough Draw-A-Man)",
    title_fr: "Test du bonhomme de Goodenough / Harris",
    category: "psychologie",
    category_label: "النضج العقلي والإسقاطي",
    age_range: "3 - 13 سنة",
    duration: "15 دقيقة",
    source: "CREAPSY / Base comp 🇩🇿",
    dimensions: ["اكتمال أجزاء الجسم (الرأس، الأطراف، الملامح)", "تناسب الأحجام والنسب الجسمانية", "التفاصيل الدقيقة (الأصابع، الملابس، الشعر)", "التآزر الحركي ونضج الخطوط"],
    description: "رسم رجل كامل، يجمع بين قياس النضج العقلي (تحديد العمر العقلي للطفل) وفحص إدراكه للجسد وصورته الذاتية.",
    cutoff: "معيار كمي: جدول نقاط جودايناف لتحديد العمر العقلي ونسبة الذكاء المقدرة",
    color: "from-teal-600 to-indigo-700",
    icon: Smile
  },
  {
    id: "m-abc-2",
    code: "M-ABC-2",
    title_ar: "بطارية تقييم حركة الأطفال والتناسق الحركي (M-ABC-2 - Henderson)",
    title_fr: "Movement Assessment Battery for Children - 2nd Edition",
    category: "psychomotricite",
    category_label: "النمو الحركي والتناسق",
    age_range: "3 - 16 سنة",
    duration: "30 - 45 دقيقة",
    source: "CREAPSY / معيار مقنن 🇩🇿",
    dimensions: ["البراعة اليدوية والتنسيق الدقيق (Manuel Dexterity)", "مهارات الرمي والالتقاط والتصويب (Aiming & Catching)", "التوازن الحركي الثابت والديناميكي (Balance)"],
    description: "البطارية المعيارية الدولية الأولى لتشخيص عسر التناسق الحركي النمائي (الدسبراكسيا DCD / Dyspraxie).",
    cutoff: "مئين <= 5: صعوبة حركية دالة (منطقة حمراء) | 6 - 15: في دائرة الخطر (منطقة صفراء) | > 15: أداء حركي طبيعي (منطقة خضراء)",
    color: "from-emerald-600 to-teal-700",
    icon: Activity
  },
  {
    id: "zazzo",
    code: "ZAZZO",
    title_ar: "روائز زازو للتطور النفسي الحركي والجانبية (Épreuves de Zazzo)",
    title_fr: "Épreuves de développement psychomoteur de René Zazzo",
    category: "psychomotricite",
    category_label: "النفسي حركي والجانبية",
    age_range: "4 - 14 سنة",
    duration: "30 دقيقة",
    source: "CREAPSY / Base comp 🇩🇿",
    dimensions: ["فحص الجانبية التفضيلية المتجانسة أو المتصالبة (اليد، العين، القدم)", "التوجه المكاني واليمين/اليسار على الذات والآخر", "رائز الشطب لسرعة التنسيق والانتباه", "المخطط الجسدي الحركي"],
    description: "الأداة الكلاسيكية المؤسسة للعلاج النفسي حركي لتشخيص اضطراب الجانبية والتنظيم الفضائي.",
    cutoff: "تحديد الجانبية (يمينية متجانسة، يسارية، أو متصالبة) والنضج المكاني",
    color: "from-teal-600 to-cyan-800",
    icon: Activity
  },
  {
    id: "corp-r",
    code: "CORP-R",
    title_ar: "رائز فحص وتمثل المخطط الجسدي المعدل (Épreuve de schéma corporel révisée)",
    title_fr: "Épreuve de schéma corporel révisée (CORP-R / Bergès-Lézine)",
    category: "psychomotricite",
    category_label: "المخطط الجسدي",
    age_range: "3 - 11 سنة",
    duration: "20 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["تسمية أجزاء الجسم وتحديدها على الذات", "تحديد أجزاء الجسم على الفاحص بالانعكاس المرآوي", "تركيب قطع ومفاصل الجسد على لوحة بازل", "تقليد الوضعيات والحركات الجسدية المجردة"],
    description: "يقيس نضج إدراك الطفل لحدود جسده وأعضائه، وهو الركيزة الأساسية للعلاج النفسي حركي والتوازن الانفعالي.",
    cutoff: "تحديد العمر المكافئ لنمو المخطط الجسدي",
    color: "from-blue-600 to-indigo-700",
    icon: User
  },
  {
    id: "df-mot",
    code: "DF-MOT",
    title_ar: "رائز التقييم الحركي والتوازن الوظيفي للأطفال (DF-MOT)",
    title_fr: "Évaluation de la motricité fonctionnelle de l'enfant",
    category: "psychomotricite",
    category_label: "الحركية العامة والتوازن",
    age_range: "3 - 9 سنوات",
    duration: "25 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["التوازن على قدم واحدة مع فتح وإغلاق العينين", "القفز التتابعي والتوافق العضلي", "الجري الموجه وتغيير الاتجاه السريع", "التوافق بين الأطراف العلوية والسفلية"],
    description: "فحص سريري للمهارات الحركية العامة والرشاقة الحركية للأطفال ذوي التأخر النمائي.",
    cutoff: "معيار نمائي عمري",
    color: "from-emerald-600 to-teal-800",
    icon: Activity
  },
  {
    id: "emg",
    code: "EMG",
    title_ar: "تقييم المهارات البراكسية والحركية الدقيقة الطرفية (EMG - Gnosopraxies distales)",
    title_fr: "Évaluation de la motricité gnosopraxique distale",
    category: "psychomotricite",
    category_label: "البراكسيا والحركية الدقيقة",
    age_range: "4 - 10 سنوات",
    duration: "20 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الحركات المنفصلة للأصابع (معارضة الإبهام للسبابة وباقي الأصابع)", "التعرف اللمسي على الأصابع بدون نظر (Gnosie digitale)", "حركات التنسيق اليدوي المتناوبة (Diadococinésie)", "رصد الحركات المصاحبة الشاردة (Syncinésies)"],
    description: "فحص نيوروبسيكولوجي وحركي دقيق لتشخيص الدسبراكسيا النمائية وعسر استخدام اليد في الأنشطة المدرسية.",
    cutoff: "وجود سينكينيزيا واضحة بعد سن 7 سنوات يدل على عدم نضج التثبيط العصبي الحركي",
    color: "from-indigo-600 to-purple-700",
    icon: Zap
  },
  {
    id: "frostig",
    code: "FROSTIG",
    title_ar: "اختبار ماريان فروستيج لتطور الإدراك البصري والحركي (DTVP / Frostig)",
    title_fr: "Test de développement de la perception visuelle de Frostig",
    category: "psychomotricite",
    category_label: "الإدراك البصري والتآزر الحركي",
    age_range: "4 - 10 سنوات",
    duration: "30 - 45 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["التنسيق البصري الحركي (رسم خطوط دقيقة بين مسارات ضيقة)", "إدراك الشكل والأرضية (تمييز الأشكال المتداخلة)", "ثبات الشكل الهندسي في أوضاع مختلفة", "إدراك العلاقات المكانية والتوجه في الفراغ"],
    description: "البطارية المعيارية الأشهر لتشخيص مشكلات الإدراك البصري المسببة لصعوبات الكتابة والقراءة ونقل الدروس من السبورة.",
    cutoff: "معامل الإدراك البصري العام وحساب العمر الإدراكي",
    color: "from-cyan-600 to-blue-700",
    icon: Eye
  },
  {
    id: "rey-fcr",
    code: "REY-FCR",
    title_ar: "اختبار الشكل المعقد لرأي لتقييم التخطيط البصري المكاني والذاكرة (Figure de Rey)",
    title_fr: "Figure complexe de Rey (Test de copie et de reproduction de mémoire)",
    category: "psychomotricite",
    category_label: "التخطيط الفضائي والذاكرة",
    age_range: "من 4 سنوات حتى البالغين والمسنين",
    duration: "15 دقيقة (نقل مباشر + إعادة استرجاع بالذاكرة)",
    source: "CREAPSY 🇩🇿",
    dimensions: ["استراتيجية النقل (البدء بالهيكل المركزي المنظم مقابل البدء بالتفاصيل المشتتة)", "دقة وموقع العناصر الـ 18 للشكل", "الذاكرة البصرية الفورية بعد 3 دقائق", "زمن الإنجاز ومستوى النضج الإدراكي"],
    description: "أداة نيوروبسيكولوجية ونفسية حركية عالمية تكشف اضطرابات الوظائف التنفيذية، الدسبراكسيا البصرية البنائية، وضعف الذاكرة.",
    cutoff: "جدول درجات رأي المقننة (من 0 إلى 36 نقطة): أقل من المئين 10 يؤكد وجود خلل تنفيذي أو دسبراكسيا بنائية",
    color: "from-purple-700 to-indigo-900",
    icon: Brain
  },
  {
    id: "cvlt",
    code: "CVLT",
    title_ar: "اختبار كاليفورنيا للتعلم والذاكرة اللفظية (CVLT)",
    title_fr: "California Verbal Learning Test (CVLT)",
    category: "psychomotricite",
    category_label: "الذاكرة اللفظية والتعلم",
    age_range: "مراهقون وبالغون",
    duration: "30 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["منحنى التعلم والتذكر المباشر عبر المحاولات المتكررة", "استراتيجية التجميع الدلالي مقابل الحفظ العشوائي", "التذكر المؤجل بعد 20 دقيقة", "التعرف مع وجود مشتتات"],
    description: "فحص سريري معمق للذاكرة اللفظية لتشخيص اضطرابات الذاكرة بعد الصدمات أو في بدايات الزهايمر والخرف.",
    cutoff: "Z-score في التذكر الفوري والمؤجل",
    color: "from-teal-700 to-indigo-800",
    icon: Brain
  },
  {
    id: "cms",
    code: "CMS",
    title_ar: "مقياس الذاكرة الشامل للأطفال (Children's Memory Scale - CMS)",
    title_fr: "Children's Memory Scale (CMS)",
    category: "psychomotricite",
    category_label: "الذاكرة والتعلم للأطفال",
    age_range: "5 - 16 سنة",
    duration: "45 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الذاكرة اللفظية السمعية (قصص وكلمات)", "الذاكرة البصرية غير اللفظية (وجوه ومسارات)", "الذاكرة العاملة اللفظية والمكانية", "الاسترجاع الفوري مقابل المؤجل"],
    description: "البطارية النيوروبسيكولوجية الشاملة لتقييم الذاكرة عند الأطفال ومطابقتها مع مقاييس وكسلر للذكاء.",
    cutoff: "معامل الذاكرة العام (Indice de mémoire générale)",
    color: "from-indigo-600 to-purple-800",
    icon: Brain
  },
  {
    id: "nepsy-2",
    code: "NEPSY-II",
    title_ar: "البطارية النمائية العصبية الشاملة للأطفال (NEPSY-II - Korkman)",
    title_fr: "Bilan neuropsychologique de l'enfant (NEPSY-II)",
    category: "psychomotricite",
    category_label: "التقييم النمائي العصبي",
    age_range: "3 - 16 سنة",
    duration: "60 - 90 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الانتباه والوظائف التنفيذية", "اللغة والمعالجة الفونولوجية", "الذاكرة والتعلم", "المعالجة البصرية المكانية", "الإدراك الحركي والتناسق", "الإدراك الاجتماعي ونظرية العقل"],
    description: "أضخم وأشمل بطارية تقييم عصبي نفسي للأطفال لتقديم خريطة دقيقة لوظائف الدماغ المعرفية والحركية.",
    cutoff: "بروفيل عصبي نفسي معياري في 6 مجالات نمائية",
    color: "from-violet-700 to-blue-700",
    icon: Brain
  },
  {
    id: "bat-neur",
    code: "BAT-NEUR",
    title_ar: "البطارية العيادية للفحص والتقييم النيوروبسيكولوجي العصبي (BAT-NEUR)",
    title_fr: "Batterie d'évaluation neuropsychologique",
    category: "psychomotricite",
    category_label: "الفحص العصبي النفسي",
    age_range: "أطفال، مراهقون، وبالغون",
    duration: "50 دقيقة",
    source: "CREAPSY 🇩🇿",
    dimensions: ["الانتباه المركز والموزع", "الوظائف الجبهية والتخطيط", "الذاكرة المباشرة والتراجعية", "البراكسيا والتعرف الحسي البصري"],
    description: "فحص متكامل مستخدم في العيادات النيوروبسيكولوجية الجزائرية للكشف عن آثار الإصابات الدماغية والاضطرابات المعرفية.",
    cutoff: "مؤشر عجز عصبي معرفي",
    color: "from-blue-700 to-indigo-900",
    icon: Activity
  },
];

export const CLINICAL_PROTOCOLS_CATALOG = [
  {
    id: 'ex-oral-motor',
    title: 'برنامج تقوية عضلات النطق والفم واللسان (Oral Motor Protocol)',
    category: 'orthophony',
    category_label: 'الأرطوفونيا والنطق',
    target: 'علاج الديسلثريا، اضطراب مخارج الحروف، وتقوية عضلات المضغ والبلع',
    difficulty: 'مبتدئ إلى متوسط',
    frequency: '3 مرات أسبوعياً (15 دقيقة)',
    materials: 'مرآة تدريب، بطاقات صور الحركات، خافض لسان طبي',
    steps: [
      'تمرين رفع وخفض اللسان نحو سقف الحلق والفك السفلي مع التثبيت 5 ثوانٍ.',
      'تمرين تحريك اللسان دائرياً حول الشفتين مع المقاومة الخفيفة.',
      'تمرين نفخ الخدين بالتناوب وحبس الهواء لتحسين الإغلاق الشفوي.',
      'تمرين اهتزاز الشفتين واللسان لتهيئة نطق صوت الراء /r/ والأصوات الانفجارية.'
    ],
    color: 'from-rose-500 to-amber-600'
  },
  {
    id: 'ex-easy-onset',
    title: 'تقنية البداية السهلة وتمديد الأصوات لمرضى التأتأة (Easy Onset & Prolongation)',
    category: 'fluency',
    category_label: 'طلاقة النطق والتأتأة',
    target: 'تقليل الوقفات اللاإرادية والتشنج الحنجري في بداية الكلمات',
    difficulty: 'متوسط إلى متقدم',
    frequency: 'يومياً (10 دقائق صباحاً ومساءً)',
    materials: 'مؤقت إيقاعي، قائمة كلمات تبدأ بحروف لينة وحروف مد',
    steps: [
      'أخذ نفس بطني عميق مع استرخاء الكتفين والحنجرة.',
      'إخراج صوت خافت ومستمر مثل /h/ أو الهمس قبل نطق الكلمة المستهدفة.',
      'تمديد الصوت الصامت الأول لمدة ثانيتين برفق دون ضغط عضلي.',
      'دمج التقنية في جمل قصيرة ثم الحوار التفاعلي التلقائي.'
    ],
    color: 'from-amber-500 to-orange-600'
  },
  {
    id: 'ex-pecs-schedule',
    title: 'نظام التواصل بالصور والروتين البصري (PECS Phase I - III)',
    category: 'autism',
    category_label: 'التوحد وتعديل السلوك',
    target: 'تطوير التواصل الوظيفي التلقائي والطلب التعبيري لأطفال طيف التوحد',
    difficulty: 'مبتدئ',
    frequency: 'مستمر خلال اليوم العلاجي والمنزلي',
    materials: 'كتاب التواصل PECS، بطاقات الأطعمة والألعاب والأنشطة',
    steps: [
      'المرحلة 1: التدريب على إعطاء البطاقة للمدرب للحصول على المعزز المفضل.',
      'المرحلة 2: زيادة المسافة والبحث عن كتاب التواصل والوصول للمتلقي.',
      'المرحلة 3: التمييز البصري بين بطاقتين (شيء مرغوب وشيء غير مرغوب).',
      'بناء شريط الجملة التعبيرية "أنا أريد + [البطاقة]".'
    ],
    color: 'from-blue-600 to-indigo-600'
  },
  {
    id: 'ex-phonological-blend',
    title: 'تدريب الوعي الفونولوجي والدمج الصوتي (Phonological Blending)',
    category: 'learning',
    category_label: 'صعوبات التعلم والديسلكسيا',
    target: 'تحسين سرعة القراءة والتهجئة والتمييز بين المقاطع الصوتية المتشابهة',
    difficulty: 'متوسط',
    frequency: '4 مرات أسبوعياً (20 دقيقة)',
    materials: 'مكعبات الأصوات الملونة، بطاقات الكلمات المجزأة',
    steps: [
      'تفكيك الكلمة المسموعة إلى أصوات منفردة (مثال: ك - ت - ا - ب).',
      'دمج الأصوات المسموعة بسرعة لتكوين الكلمة الصحيحة.',
      'التعرف على الصوت الأولي والأوسط والأخير في الكلمات.',
      'حذف أو استبدال صوت لتكوين كلمة جديدة (التلاعب الفونيمي).'
    ],
    color: 'from-emerald-500 to-teal-600'
  },
  {
    id: 'ex-attention-stroop',
    title: 'تمارين تعزيز الانتباه الانتقائي وكبح الاندفاعية (Stroop & Inhibition)',
    category: 'adhd',
    category_label: 'تشتت الانتباه وفرط الحركة',
    target: 'تنمية الوظائف التنفيذية والتحكم الذاتي وتأخير الاستجابة الاندفاعية',
    difficulty: 'متوسط إلى متقدم',
    frequency: '3 مرات أسبوعياً',
    materials: 'بطاقات شتروب الملونة، تطبيق المؤقت البصري',
    steps: [
      'قراءة لون الكلمة المكتوبة بدلاً من قراءة الكلمة نفسها (تأثير شتروب).',
      'تمرين الإيقاف والانطلاق (Go / No-Go) عند ظهور الإشارة الخضراء أو الحمراء.',
      'البحث البصري عن الأشكال المتطابقة في مصفوفة مشتتة زمنياً.',
      'تمرين الذاكرة العاملة التراجعية (تكرار الأرقام بالترتيب العكسي).'
    ],
    color: 'from-purple-600 to-pink-600'
  },
  {
    id: 'ex-breathing-relaxation',
    title: 'برنامج التنفس الحجابي والاسترخاء العضلي التدريجي (Jacobson Relaxation)',
    category: 'psychology',
    category_label: 'علم النفس والقلق السلوكي',
    target: 'خفض مستويات القلق والتوتر المصاحب للجلسات والتأتأة والامتحانات',
    difficulty: 'مبتدئ',
    frequency: 'يومياً قبل النوم وعند الشعور بالتوتر',
    materials: 'بيئة هادئة، إرشادات صوتية مهدئة',
    steps: [
      'الاستلقاء أو الجلوس المريح مع وضع اليد على البطن وأخرى على الصدر.',
      'أخذ شهيق عميق من الأنف لمدة 4 ثوانٍ مع انتفاخ البطن.',
      'حبس النفس لمدة ثانيتين ثم إخراج الزفير ببطء من الفم لمدة 6 ثوانٍ.',
      'شد عضلات اليدين والوجه ثم إرخائها تدريجياً لملاحظة الفرق في الراحة.'
    ],
    color: 'from-cyan-600 to-blue-700'
  },
  {
    id: 'ex-bilateral-balance',
    title: 'مسارات التوازن الحركي والتناسق الثنائي (Bilateral Coordination Tracks)',
    category: 'psychomotricite',
    category_label: 'التأهيل النفسي الحركي',
    target: 'تطوير التوازن الحركي، التوافق العضلي العصبي، وعلاج عسر الحركة (Dyspraxie)',
    difficulty: 'متوسط',
    frequency: '3 مرات أسبوعياً (25 دقيقة)',
    materials: 'ألواح التوازن الخشبية، دوائر حركية أرضية، كرات مطاطية',
    steps: [
      'المشي على خط مستقيم ثم خط متعرج مع وضع كعب القدم أمام أصابع القدم الأخرى.',
      'الوقوف على قدم واحدة على لوح التوازن لمدة 10 ثوانٍ مع إغلاق العينين.',
      'تبادل رمي والتقاط الكرة بكلتا اليدين أثناء القفز داخل الدوائر الأرضية.',
      'تمارين الزحف المتقاطع المعاكس (اليد اليمنى مع الركبة اليسرى والعكس).'
    ],
    color: 'from-emerald-600 to-teal-700'
  },
  {
    id: 'ex-social-skills',
    title: 'تدريب المهارات الاجتماعية والتواصل البصري وتبادل الأدوار (Social Stories)',
    category: 'autism',
    category_label: 'المهارات الاجتماعية والتواصل',
    target: 'تطوير المبادأة في المحادثة، فهم الإشارات غير اللفظية، والاندماج المدرسي',
    difficulty: 'متوسط',
    frequency: 'مرتان أسبوعياً',
    materials: 'قصص اجتماعية مصورة، بطاقات تعابير الوجه، ألعاب الأدوار',
    steps: [
      'قراءة القصة الاجتماعية حول "كيف أحيي زملائي وأطلب اللعب معهم".',
      'تمثيل الأدوار (Role-playing) وتدريب الطفل على التواصل البصري لمدة 5 ثوانٍ.',
      'تفسير تعابير الوجه الأربعة الأساسية (سعيد، حزين، غاضب، خائف).',
      'تدريب على قاعدة "انتظار الدور" في الألعاب الجماعية باستخدام بطاقة الدور.'
    ],
    color: 'from-indigo-600 to-blue-700'
  },
  {
    id: 'ex-working-memory-dual',
    title: 'تدريب الذاكرة العاملة المزدوجة السمعية والبصرية (Dual N-Back Protocol)',
    category: 'adhd',
    category_label: 'الذاكرة العاملة والتركيز',
    target: 'توسيع سعة التخزين المؤقت في الذاكرة ومقاومة النسيان السريع أثناء الحفظ',
    difficulty: 'متقدم',
    frequency: 'يومياً (15 دقيقة)',
    materials: 'شبكة أرقام وحروف، تسلسل بطاقات ملونة',
    steps: [
      'المستوى 1: تكرار 3 أرقام مسموعة بنفس الترتيب، ثم بالترتيب العكسي.',
      'المستوى 2: تذكر مكان المربع المضاء قبل خطوة واحدة (1-Back).',
      'المستوى 3: الاستماع لقائمة كلمات وتحديد الكلمة التي بدأت بحرف محدد.',
      'المستوى 4: تنفيذ تعليمتين مركبتين متتاليتين دون إعادة التوجيه.'
    ],
    color: 'from-purple-600 to-indigo-800'
  },
  {
    id: 'ex-pincer-grasp',
    title: 'تمارين تقوية عضلات الأصابع والقبض الثلاثي لمسك القلم (Pincer Grasp)',
    category: 'psychomotricite',
    category_label: 'عسر الكتابة والحركية الدقيقة',
    target: 'علاج إجهاد اليد أثناء الكتابة وتحسين جودة ووضوح الخط والتحكم بالقلم',
    difficulty: 'مبتدئ إلى متوسط',
    frequency: '4 مرات أسبوعياً (15 دقيقة)',
    materials: 'صلصال طبي بمقاومات مختلفة، ملاقط خشبية، خرز، مقص أمان',
    steps: [
      'عجن وضغط الصلصال الطبي بالأصابع الثلاثة الرئيسية (الإبهام والسبابة والوسطى).',
      'التقاط الكرات الصغيرة بواسطة الملقط ونقلها إلى أوعية ملونة متطابقة.',
      'قص أوراق تتبع الخطوط المستقيمة والمنحنية بالمقص الطبي المساعد.',
      'تلوين داخل مساحات ضيقة دون الخروج عن الإطار المحدد بقلم سميك مريح.'
    ],
    color: 'from-teal-600 to-emerald-700'
  },
  {
    id: 'ex-token-behavior',
    title: 'نظام اللوحة الرمزية والتعزيز السلوكي المنزلي (Token Economy Board)',
    category: 'autism',
    category_label: 'تعديل السلوك والتحفيز',
    target: 'تقليل نوبات العناد وزيادة الامتثال للمهام اليومية والدراسية في المنزل',
    difficulty: 'مبتدئ',
    frequency: 'مستمر يومياً',
    materials: 'لوحة نجوم مغناطيسية، صور المكافآت المرغوبة',
    steps: [
      'الاتفاق مع الطفل مسبقاً على السلوك الإيجابي المطلوب (مثال: الجلوس 15 دقيقة لحل الواجب).',
      'منح نجمة أو رمز فوري عند إنجاز المهمة بنجاح مع التعزيز اللفظي.',
      'استبدال 5 نجوم بمكافأة متفق عليها (مثال: نصف ساعة لعب مفضل أو نزهة).',
      'عدم سحب النجوم المكتسبة أبداً لتجنب الإحباط، والتركيز على التعزيز الإيجابي.'
    ],
    color: 'from-amber-500 to-pink-600'
  },
  {
    id: 'ex-auditory-discrimination',
    title: 'تدريب التمييز السمعي للأصوات المتشابهة في بيئة ضوضائية (Auditory Training)',
    category: 'orthophony',
    category_label: 'التمييز السمعي واللغة',
    target: 'معالجة الخلط بين الحروف المتقاربة في المخرج (س/ش، ك/ق، د/ط)',
    difficulty: 'متوسط',
    frequency: '3 مرات أسبوعياً',
    materials: 'سماعات رأس، تسجيلات كلمات ثنائية صغرى (Paires Minimales)',
    steps: [
      'الاستماع لكلمتين متقاربتين (مثال: سَمين / شَمين) وتحديد الصوت المختلف.',
      'رفع البطاقة المناسبة عند سماع الكلمة المستهدفة بين أصوات مشتتة.',
      'تكرار الكلمات تحت خلفية ضوضائية خفيفة لمحاكاة بيئة القسم المدرسي.',
      'الربط بين الصوت المسموع والحرف المكتوب لترسيخ الذاكرة الفونولوجية.'
    ],
    color: 'from-blue-600 to-teal-700'
  },
  {
    id: 'ex-resonant-voice',
    title: 'برنامج الصوت الرنان وتقليل الجهد الحنجري (Resonant Voice Therapy)',
    category: 'orthophony',
    category_label: 'التأهيل الصوتي والبحة',
    target: 'علاج بحة الصوت والإجهاد الصوتي وعقد الأحبال الصوتية (Nodules)',
    difficulty: 'متوسط',
    frequency: 'يومياً (15 دقيقة)',
    materials: 'أنبوب ماء زجاجي، نغمات صوتية مستمرة',
    steps: [
      'تمرين النفخ والهمهمة بالصوت عبر قشة في كوب ماء (Lax Vox Protocol).',
      'إصدار صوت "مِمممم" ممتد مع الشعور بالرنين والاهتزاز في جسر الأنف والشفاه.',
      'الانتقال من النغمات الأحادية إلى الكلمات اليومية مع المحافظة على خفة الصوت.',
      'تجنب الصراخ وتنظيف الحلق بحركات قاسية، وشرب كميات كافية من الماء.'
    ],
    color: 'from-rose-600 to-amber-700'
  },
  {
    id: 'ex-cbt-thought-diary',
    title: 'سجل مذكرات الأفكار التلقائية وإعادة الهيكلة المعرفية (CBT Thought Record)',
    category: 'psychology',
    category_label: 'العلاج المعرفي السلوكي',
    target: 'رصد وتعديل الأفكار الكارثية والتشوهات المعرفية المسببة للقلق والاكتئاب',
    difficulty: 'متوسط إلى متقدم',
    frequency: 'عند حدوث أي نوبة توتر أو ضيق انفعالي',
    materials: 'جدول الأعمدة الخمسة لبيك، دليل التشوهات المعرفية',
    steps: [
      'تحديد الموقف المثير (ماذا حدث بالتحديد؟ وأين ومتى؟).',
      'تحديد الفكرة التلقائية المشوهة (ماذا قلت لنفسي في تلك اللحظة؟).',
      'تسمية المشاعر الناتجة وتقييم شدتها من 0 إلى 100%.',
      'البحث عن الأدلة الواقعية المؤيدة والمعارضة لهذه الفكرة.',
      'صياغة فكرة بديلة عقلانية ومتزنة وإعادة تقييم شدة الانفعال.'
    ],
    color: 'from-purple-700 to-indigo-900'
  },
  {
    id: 'ex-dyslexia-syllabic',
    title: 'برنامج القراءة المقطعية والنصوص المتدرجة لعسر القراءة (Syllabic Reading)',
    category: 'learning',
    category_label: 'علاج الديسلكسيا',
    target: 'بناء الطلاقة القرائية وتسهيل دمج المقاطع في الكلمات متعددة المقاطع',
    difficulty: 'متوسط',
    frequency: 'يومياً (15 دقيقة قراءة موجهة)',
    materials: 'نصوص ملونة بالتناوب المقطعي، مسطرة قراءة بصرية',
    steps: [
      'تلوين مقاطع الكلمات بلونين متناوبين (مثال: المقطع الأول أزرق والثاني أحمر).',
      'تغطية الكلمات اللاحقة بمسطرة القراءة والتركيز على المقطع المنظور فقط.',
      'القراءة الثنائية المتزامنة مع الأخصائي (Choral Reading) لضبط السرعة.',
      'إعادة قراءة نفس الفقرة 3 مرات لقياس تطور سرعة القراءة بالدقائق.'
    ],
    color: 'from-amber-600 to-emerald-700'
  },
  {
    id: 'ex-spatial-time-sequence',
    title: 'برنامج التسلسل الزماني والمكاني والقصص التتابعية (Temporal Sequences)',
    category: 'psychomotricite',
    category_label: 'التنظيم المكاني الزماني',
    target: 'معالجة التشتت في إدراك تعاقب الأحداث وفهم مفاهيم (الماضي، الحاضر، والمستقبل)',
    difficulty: 'مبتدئ إلى متوسط',
    frequency: '3 مرات أسبوعياً',
    materials: 'بطاقات قصص متسلسلة (3 إلى 6 بطاقات)، جدول الأيام والشهور',
    steps: [
      'ترتيب بطاقات القصة المصورة من اليمين إلى اليسار وفق التتابع المنطقي.',
      'سرد أحداث القصة باستخدام أدوات الربط: (في البداية، ثم، بعد ذلك، وأخيراً).',
      'تحديد ما حدث "قبل" و "بعد" حدث معين في القصة.',
      'تمثيل جدول الروتين اليومي وربطه بساعة الحائط والأنشطة الواقعية.'
    ],
    color: 'from-cyan-600 to-indigo-800'
  },
];
