import {
  Volume2,
  Brain,
  Stethoscope,
  Activity,
  Zap,
  BookOpen,
  MessageSquare,
  Sparkles,
  HeartPulse,
  Eye,
  Smile,
  Frown,
  Scale,
  ShieldAlert,
  Layers,
  Award,
  CheckCircle2,
  Clock,
  User,
  Music,
} from 'lucide-react';

// =========================================================================
// CLINICAL TESTS & PROTOCOLS CATALOG (+48 STANDARDIZED CLINICAL TESTS)
// =========================================================================
export const CLINICAL_TESTS_CATALOG = [
  // --- 1. SPEECH, LANGUAGE & FLUENCY (الأرطوفونيا واللغة والطلاقة) ---
  {
    id: 'ssi-4',
    code: 'SSI-4',
    title_ar: 'مقياس شدة التأتأة عند الأطفال والبالغين (Riley)',
    title_fr: 'Stuttering Severity Instrument - 4th Edition',
    category: 'fluency',
    category_label: 'طلاقة الكلام والتأتأة',
    age_range: '3 سنوات فما فوق (أطفال وبالغون)',
    duration: '20 - 30 دقيقة',
    dimensions: ['تكرار المقاطع والأصوات', 'الوقفات اللاإرادية (Blocks)', 'الحركات الجسدية المصاحبة', 'مدة التعثر بالثواني'],
    description: 'الأداة المعيارية الذهبية لتقييم وقياس درجة شدة التأتأة وتحديد النسبة المئوية للتعثر أثناء القراءة والحديث العفوي.',
    cutoff: 'طبيعي < 10 | خفيف: 11-17 | متوسط: 18-24 | شديد: 25-31 | حاد جداً: > 32',
    color: 'from-amber-500 to-rose-600',
    icon: Volume2
  },
  {
    id: 'test-artic-dz',
    code: 'TEST-ARTIC-DZ',
    title_ar: 'رائز فحص مخارج الأصوات والحروف باللهجة الجزائرية والفصحى',
    title_fr: 'Test d\'Articulation et de Phonologie (Normes DZ)',
    category: 'orthophony',
    category_label: 'النطق والأرطوفونيا',
    age_range: '3 - 10 سنوات',
    duration: '15 - 25 دقيقة',
    dimensions: ['الأصوات الصامتة (أول/وسط/آخر الكلمة)', 'التشويه والحذف والإبدال', 'التمييز السمعي الفونولوجي', 'المرونة اللسانية'],
    description: 'فحص سريري شامل لكافة الفونيمات مع صور وبطاقات مكيفة مع البيئة والقاموس اللغوي الجزائري.',
    cutoff: 'نسبة الدقة: طبيعي > 90% | تأخر نطقي خفيف: 75-89% | اضطراب نطقي دال: < 75%',
    color: 'from-emerald-500 to-teal-600',
    icon: Stethoscope
  },
  {
    id: 'teld-3',
    code: 'TELD-3',
    title_ar: 'اختبار التطور اللغوي الشامل (اللغة الاستقبالية والتعبيرية)',
    title_fr: 'Test of Early Language Development (TELD-3)',
    category: 'orthophony',
    category_label: 'تأخر النمو اللغوي',
    age_range: '2 - 8 سنوات',
    duration: '25 - 35 دقيقة',
    dimensions: ['اللغة الاستقبالية والفهم', 'اللغة التعبيرية والتركيب', 'القاموس الدلالي والمفردات', 'النحو والصرف'],
    description: 'يقيس بدقة العمر اللغوي للطفل مقارنة بعمره الزمني وتحديد نسبة التأخر في اكتساب مهارات التخاطب.',
    cutoff: 'حساب المعامل اللغوي (Spoken Language Quotient) - انحراف معياري -1.5 SD دال على التأخر',
    color: 'from-sky-600 to-blue-700',
    icon: MessageSquare
  },
  {
    id: 'elo',
    code: 'ELO',
    title_ar: 'تقييم اللغة الشفهية عند الطفل (Évaluation du Langage Oral)',
    title_fr: 'Batterie ELO (Vocabulaire, Syntaxe & Compréhension)',
    category: 'orthophony',
    category_label: 'اللغة الشفهية والتواصل',
    age_range: '3 - 11 سنة',
    duration: '30 - 45 دقيقة',
    dimensions: ['المعجم الاستقبالي والتعبيري', 'التراكيب النحوية وتوليد الجمل', 'التكرار الفوري للجمل والكلمات الزائفة'],
    description: 'بطارية معيارية لتقييم المكونات الثلاثة للغة الشفهية وكشف العسر اللغوي النوعي (Dysphasie / TSLO).',
    cutoff: 'درجات معيارية Z-Scores لكل مؤشر - درجات أقل من -2 دالة على اضطراب نمائي لغوي',
    color: 'from-blue-600 to-indigo-700',
    icon: MessageSquare
  },
  {
    id: 'alouette-r',
    code: 'ALOUETTE-R',
    title_ar: 'رائز علوة المعياري لسرعة ودقة فك الشفرة القرائية (L\'Alouette)',
    title_fr: 'Test de Lecture de l\'Alouette - Révisé',
    category: 'learning',
    category_label: 'صعوبات التعلم والديسلكسيا',
    age_range: '6 - 15 سنة',
    duration: '3 دقائق فقط (موقوت)',
    dimensions: ['زمن القراءة الكلي بالثواني', 'عدد الكلمات المقروءة بدقة', 'عدد الأخطاء والإبدالات', 'مؤشر الكفاءة القرائية (ELP)'],
    description: 'الرائز الأكثر شهرة واعتماداً في العالم الفرنكوفوني لقياس دقة وسرعة فك الرموز القرائية وتشخيص الديسلكسيا.',
    cutoff: 'تحديد العمر القرائي (Âge Lexique) - فارق أكثر من 18 شهراً عن العمر الزمني دال على عسر القراءة',
    color: 'from-amber-600 to-orange-600',
    icon: BookOpen
  },
  {
    id: 'l2ma-2',
    code: 'L2MA-2',
    title_ar: 'بطارية فحص اللغة المكتوبة والوعي الفونولوجي (L2MA-2)',
    title_fr: 'Batterie Langage Écrit & Phonologie (L2MA-2)',
    category: 'learning',
    category_label: 'صعوبات القراءة والكتابة',
    age_range: '7 - 14 سنة',
    duration: '45 دقيقة',
    dimensions: ['قراءة الكلمات العادية والشا Regex', 'قراءة الكلمات غير المألوفة', 'الإملاء والقواعد الإملائية', 'التحليل الفونولوجي والتقطيع'],
    description: 'تحليل دقيق للمسارين الإجرائيين للقراءة: المسار الفونولوجي (المباشر) والمسار المعجمي (البصري).',
    cutoff: 'رصد نوع الديسلكسيا: فونولوجية (Phonologique) / سطحية (De surface) / مختلطة (Mixte)',
    color: 'from-orange-600 to-amber-700',
    icon: BookOpen
  },
  {
    id: 'zareki-r',
    code: 'ZAREKI-R',
    title_ar: 'بطارية فحص عسر الحساب والمهارات الرياضية للأطفال (ZAREKI-R)',
    title_fr: 'Batterie pour l\'Évaluation du Traitement des Nombres (ZAREKI-R)',
    category: 'learning',
    category_label: 'عسر الحساب (Dyscalculie)',
    age_range: '6 - 11 سنة',
    duration: '40 دقيقة',
    dimensions: ['عد الأشياء والتسلسل العددي', 'قراءة وكتابة الأرقام بالأرقام والحروف', 'الحساب الذهني والآلي', 'المقارنة الفراغية للأحجام والكميات'],
    description: 'أداة سريرية متخصصة في الكشف والتشخيص الدقيق لعسر الحساب التنموي (Dyscalculie Développementale).',
    cutoff: 'الرتبة المئينية < 15 دالة على عجز في معالجة الأرقام والخط العددي الذهني',
    color: 'from-rose-600 to-pink-700',
    icon: Scale
  },
  {
    id: 'do-80',
    code: 'DO-80',
    title_ar: 'رائز التسمية السريعة للصور والمعجم اللفظي (DO 80 - Deloche)',
    title_fr: 'Test de Dénomination Orale d\'Images (DO 80)',
    category: 'orthophony',
    category_label: 'المعجم والطلاقة اللفظية',
    age_range: '5 سنوات إلى سن الشيخوخة',
    duration: '15 دقيقة',
    dimensions: ['80 صورة بالأبيض والأسود', 'زمن الرجع للاستجابة بالثواني', 'أخطاء التشويه الدلالي والفونيمي', 'تأثير التلميح الصوتي والدلالي'],
    description: 'يقيس كفاءة الوصول إلى المعجم الذهني وسرعة استرجاع الكلمات وتشخيص العَمَه التسموي (Anomie).',
    cutoff: 'عدد الأخطاء > 10 عند البالغين أو > 15 عند الأطفال يشير إلى اضطراب استرجاع لفظي',
    color: 'from-indigo-600 to-teal-700',
    icon: Volume2
  },
  {
    id: 'bdae-mt86',
    code: 'MT-86',
    title_ar: 'بروتوكول فحص الحبسة الكلامية واضطرابات اللغة المكتسبة (MT-86 / BDAE)',
    title_fr: 'Protocole Montréal-Toulouse d\'Évaluation des Aphasies',
    category: 'orthophony',
    category_label: 'الحبسة والاضطرابات العصبية',
    age_range: 'البالغون والراشدون (16+ سنة)',
    duration: '45 - 60 دقيقة',
    dimensions: ['التعبير الشفهي العفوي', 'الفهم الشفهي للأوامر', 'التكرار وتسمية الأشياء', 'القراءة والفهم المكتوب والتعبير الكتابي'],
    description: 'الفحص المرجعي للمرضى بعد الجلطات الدماغية لتحديد نوع الحبسة (بروكا، فيرنيكه، شاملة، موصلية).',
    cutoff: 'تحديد درجة شدة الحبسة وملف العجز اللغوي العصبي المتبقي للتأهيل',
    color: 'from-slate-700 to-indigo-900',
    icon: Activity
  },
  {
    id: 'vhi-voice',
    code: 'VHI-10',
    title_ar: 'مؤشر إعاقة الصوت السريري وتقييم بحة الأحبال الصوتية (Voice Handicap Index)',
    title_fr: 'Voice Handicap Index (VHI-10)',
    category: 'orthophony',
    category_label: 'اضطرابات الصوت والبحة',
    age_range: 'المراهقون والبالغون',
    duration: '10 دقائق',
    dimensions: ['المجال الوظيفي (تأثير الصوت في التواصل اليومي)', 'المجال الجسدي (الإجهاد وألم الحنجرة)', 'المجال الانفعالي (الإحباط والقلق)'],
    description: 'استبيان مقنن لتقييم تأثير خلل الصوت والديسفونيا (Dysphonie) على حياة المفحوص وجودة صوته.',
    cutoff: 'الدرجة الكلية 0-10: طبيعي | 11-20: إعاقة صوتية خفيفة | 21-30: متوسطة | > 30: شديدة',
    color: 'from-amber-600 to-rose-700',
    icon: Volume2
  },
  {
    id: 'bilan-deglutition',
    code: 'DEGLUT-EXAM',
    title_ar: 'فحص البلع غير النمطي والوظائف الفموية العضلية (Examen de Déglutition)',
    title_fr: 'Évaluation Clinique de la Déglutition Atypique & Praxies',
    category: 'orthophony',
    category_label: 'عضلات الفم والبلع',
    age_range: '4 سنوات فما فوق',
    duration: '20 دقيقة',
    dimensions: ['موضع اللسان أثناء البلع (دفع أمامي/جانبي)', 'انقباض عضلة الذقن والشفتين', 'التنفس الفموي المستمر', 'سوء إطباق الأسنان'],
    description: 'بروتوكول فحص حركات اللسان والشفتين أثناء بلع اللعاب والماء والأطعمة الصلبة لإعداد تأهيل عضلي وظيفي.',
    cutoff: 'تصنيف: بلع نمطي ناضج / بلع طفولي غير نمطي مع دفع لساني يستدعي التأهيل',
    color: 'from-teal-600 to-emerald-700',
    icon: Stethoscope
  },
  {
    id: 'vocim',
    code: 'VOCIM',
    title_ar: 'رائز المفردات المصورة والذكاء اللفظي الاستقبالي (VOCIM)',
    title_fr: 'Vocabulaire en Images (Test de Vocabulaire Réceptif)',
    category: 'orthophony',
    category_label: 'المعجم اللغوي للأطفال',
    age_range: '3 - 8 سنوات',
    duration: '15 دقيقة',
    dimensions: ['تسمية واختيار الصور المعبرة', 'المعجم الاسمي والفواكه والحيوانات', 'الأفعال والصفات الشائعة'],
    description: 'يقيس رصيد المفردات الفهمية لدى الأطفال دون اشتراط إنتاج لفظي (مثالي للأطفال غير الناطقين).',
    cutoff: 'مقارنة الدرجة بالعمر الزمني لتحديد ما إذا كان الطفل يقع ضمن الرتبة الطبيعية',
    color: 'from-cyan-600 to-blue-800',
    icon: MessageSquare
  },

  // --- 2. AUTISM & NEURODEVELOPMENT (التوحد والنمو العصبي) ---
  {
    id: 'cars-2',
    code: 'CARS-2',
    title_ar: 'مقياس تقدير التوحد الطفولي (نسخة المعيار الجزائري والعربي)',
    title_fr: 'Childhood Autism Rating Scale - 2nd Edition',
    category: 'autism',
    category_label: 'اضطرابات طيف التوحد',
    age_range: '2 - 14 سنة',
    duration: '30 - 45 دقيقة',
    dimensions: ['العلاقات مع الناس', 'التقليد والتواصل البصري', 'الاستجابة الانفعالية', 'استخدام الجسد والأشياء', 'التواصل اللفظي وغير اللفظي'],
    description: 'مقياس تشخيصي إكلينيكي مكون من 15 بنداً سلوكياً لفرز وتصنيف درجات طيف التوحد بدقة معيارية.',
    cutoff: '< 30: غير توحدي | 30 - 36.5: توحد خفيف إلى متوسط | > 37: توحد شديد دال',
    color: 'from-blue-600 to-indigo-600',
    icon: Brain
  },
  {
    id: 'gars-3',
    code: 'GARS-3',
    title_ar: 'مقياس جليام لتشخيص اضطراب التوحد - الإصدار الثالث (GARS-3)',
    title_fr: 'Gilliam Autism Rating Scale - 3rd Edition',
    category: 'autism',
    category_label: 'طيف التوحد (DSM-5)',
    age_range: '3 - 22 سنة',
    duration: '20 دقيقة',
    dimensions: ['السلوكيات النمطية المقيدة', 'التفاعل الاجتماعي', 'التواصل الاجتماعي', 'الاستجابات العاطفية', 'الأسلوب المعرفي'],
    description: 'أداة تشخيصية سريعة مبنية على معايير DSM-5 لحساب معامل التوحد ونسبة الاحتمالية السريرية.',
    cutoff: 'معامل التوحد (Autism Index): < 54 مستبعد | 55-70 محتمل | > 70 مؤكد وواضح إكلينيكياً',
    color: 'from-teal-600 to-cyan-700',
    icon: Brain
  },
  {
    id: 'm-chat-rf',
    code: 'M-CHAT-R/F',
    title_ar: 'استبيان الفرز المبكر لاضطراب طيف التوحد عند الرضع والأطفال الصغار',
    title_fr: 'Modified Checklist for Autism in Toddlers - Revised / Follow-up',
    category: 'autism',
    category_label: 'الكشف والفرز المبكر',
    age_range: '16 - 30 شهراً',
    duration: '10 دقائق',
    dimensions: ['الانتباه المشترك والإشارة بالأصبع', 'التواصل البصري عند نداء الاسم', 'اللعب التخيلي التظاهري', 'الاستجابة لابتسامة الوالدين'],
    description: 'الأداة العالمية رقم 1 للفحص المبكر لعلامات التوحد في عيادات طب الأطفال والأرطوفونيا.',
    cutoff: '0-2 نقاط: خطورة منخفضة | 3-7 نقاط: خطورة متوسطة تستدعي المقابلة | 8-20: خطورة مرتفعة للتوحد',
    color: 'from-rose-500 to-amber-600',
    icon: ShieldAlert
  },
  {
    id: 'vineland-2',
    code: 'VINELAND-II',
    title_ar: 'مقياس فاينلاند للسلوك التكيفي والمهارات الاستقلالية (Vineland-II)',
    title_fr: 'Échelle de Comportement Adaptatif de Vineland',
    category: 'autism',
    category_label: 'السلوك التكيفي والاستقلالية',
    age_range: 'الولادة إلى سن الرشد (0 - 90 سنة)',
    duration: '45 - 60 دقيقة',
    dimensions: ['مجال التواصل (استقبالي، تعبيري، كتابي)', 'مهارات الحياة اليومية (شخصية، منزلية، مجتمعية)', 'التنشئة الاجتماعية والعلاقات', 'المهارات الحركية الكبرى والدقيقة'],
    description: 'المقياس المعتمد دولياً لتحديد مستوى الاستقلالية النمائية والتشخيص الفارق للإعاقة الذهنية والتوحد.',
    cutoff: 'حساب الدرجة المعيارية الكلية للتكيف (ABC): متوسط 100، انحراف معياري 15',
    color: 'from-indigo-600 to-purple-800',
    icon: Activity
  },
  {
    id: 'csbs-dp',
    code: 'CSBS-DP',
    title_ar: 'مقياس التواصل والسلوك الرمزي للتدخل المبكر (Wetherby & Prizant)',
    title_fr: 'Communication and Symbolic Behavior Scales Developmental Profile',
    category: 'autism',
    category_label: 'التواصل واللغة المبكرة',
    age_range: '6 - 24 شهراً',
    duration: '20 دقيقة',
    dimensions: ['المركب الاجتماعي (العواطف، التحديق، استخدام الإيماءات)', 'المركب اللفظي (الأصوات، الكلمات الأولى)', 'المركب الرمزي (فهم الأشياء، استخدام الأدوات)'],
    description: 'رصد فوري لأي انقطاع أو تباطؤ في النماء التواصلي التفاعلي قبل اكتمال السنتين.',
    cutoff: 'الرتبة المئينية أقل من 10% تشير إلى تأخر في المسار النمائي يستدعي تدخلاً عاجلاً',
    color: 'from-emerald-600 to-teal-800',
    icon: Smile
  },
  {
    id: 'short-sensory',
    code: 'SSP',
    title_ar: 'الملف الحسي المختصر لتقييم فرط ونقص الاستجابة الحسية (Winnie Dunn)',
    title_fr: 'Profil Sensoriel Court (Short Sensory Profile)',
    category: 'autism',
    category_label: 'التكامل الحسي والمعالجة الحسية',
    age_range: '3 - 14 سنة',
    duration: '15 دقيقة',
    dimensions: ['الحساسية اللمسية', 'حساسية التذوق والشم', 'الحساسية الحركية والدهليزية', 'نقص الاستجابة/البحث عن المثيرات', 'الحساسية السمعية والبصرية'],
    description: 'يكتشف العوامل الحسية المسؤولة عن نوبات الغضب والانسحاب والانزعاج من الضجيج أو الملابس.',
    cutoff: 'أداء نموذجي (Normal) / فارق محتمل (Douteux) / فارق مؤكد دال إكلينيكياً (Déficitaire)',
    color: 'from-purple-600 to-pink-700',
    icon: HeartPulse
  },
  {
    id: 'esdm-curriculum',
    code: 'ESDM-CHECK',
    title_ar: 'استمارة تتبع الأهداف النمائية لنموذج دنفر للتدخل المبكر (ESDM)',
    title_fr: 'Early Start Denver Model (ESDM Curriculum Checklist)',
    category: 'autism',
    category_label: 'التدخل السلوكي المبكر',
    age_range: '12 - 48 شهراً',
    duration: 'مستمر خلال الجلسات',
    dimensions: ['التواصل الاستقبالي والتعبيري', 'المهارات الاجتماعية والانتباه المشترك', 'التقليد الحركي والصوتي', 'الإدراك واللعب الرمزي', 'المهارات الحركية الدقيقة والعامة'],
    description: 'قائمة تدقيق مكونة من 4 مستويات نمائية لبناء الخطة التربوية الفردية وتتبع اكتساب المهارات.',
    cutoff: 'نسبة إتقان المهارات: مكتسبة (Passe) / قيد الاكتساب (Émergent) / غير مكتسبة (Échec)',
    color: 'from-cyan-600 to-blue-700',
    icon: Sparkles
  },
  {
    id: 'ados-2-grid',
    code: 'ADOS-2-GRID',
    title_ar: 'جدول الملاحظة السريرية لتشخيص التوحد والتفاعل الاجتماعي (ADOS-2 Grid)',
    title_fr: 'Grille d\'Observation Diagnostique de l\'Autisme (ADOS-2)',
    category: 'autism',
    category_label: 'التشخيص المعياري الذهبي',
    age_range: '12 شهراً إلى سن البلوغ (Module 1 - 4)',
    duration: '40 - 60 دقيقة',
    dimensions: ['التأثير الاجتماعي (Social Affect)', 'السلوكيات النمطية والاهتمامات المقيدة (RRB)', 'التواصل البصري والإيماءات المنسقة'],
    description: 'الأداة التشخيصية السريرية الأقوى عالمياً لملاحظة التفاعل العفوي في مواقف لعب ومحادثة مقننة.',
    cutoff: 'خوارزمية الدرجة المقارنة (CSS): 1-4 غير توحدي | 5-7 طيف توحد | 8-10 توحد شديد',
    color: 'from-indigo-700 to-violet-900',
    icon: Brain
  },

  // --- 3. ADHD & LEARNING DISABILITIES (فرط الحركة وصعوبات التعلم) ---
  {
    id: 'conners-3',
    code: 'CONNERS-3',
    title_ar: 'مقياس كونرز لفرط الحركة وتشتت الانتباه والاندفاعية (Conners 3rd Edition)',
    title_fr: 'Échelle d\'Évaluation du TDAH de Conners - 3ème Édition',
    category: 'adhd',
    category_label: 'فرط الحركة وتشتت الانتباه',
    age_range: '6 - 18 سنة',
    duration: '20 دقيقة',
    dimensions: ['تشتت الانتباه وعدم التركيز', 'فرط النشاط الحركي والتململ', 'الاندفاعية وضعف ضبط الذات', 'صعوبات التعلم والوظائف التنفيذية', 'العلاقات مع الأقران والأسرة'],
    description: 'الاستبيان المعياري العالمي لتقييم أعراض TDAH مع تقارير مخصصة للوالدين، المعلم، والتقرير الذاتي.',
    cutoff: 'T-Score > 65 يشير إلى دلالة إكلينيكية مرتفعة لأعراض اضطراب فرط الحركة وتشتت الانتباه',
    color: 'from-purple-600 to-pink-600',
    icon: Activity
  },
  {
    id: 'stroop-color',
    code: 'STROOP-TEST',
    title_ar: 'اختبار ستروب للانتباه الانتقائي وكبح الاندفاعية (Stroop Color-Word)',
    title_fr: 'Test d\'Interférence de Stroop (Inhibition & Attention Sélective)',
    category: 'adhd',
    category_label: 'الوظائف التنفيذية والكبح',
    age_range: '7 سنوات فما فوق والبالغون',
    duration: '10 دقائق',
    dimensions: ['لوحة قراءة الكلمات', 'لوحة تسمية الألوان', 'لوحة التداخل (قراءة لون الحبر المخالف للكلمة)', 'مؤشر الكبح الذهني (Inhibition Score)'],
    description: 'يقيس قدرة الفص الجبهي على كبح الاستجابة التلقائية ومقاومة التشتت الذهني.',
    cutoff: 'حساب زمن التداخل وعدد الأخطاء - بطء ملحوظ يشير إلى ضعف وظيفة الكبح الجبهي',
    color: 'from-amber-500 to-rose-600',
    icon: Zap
  },
  {
    id: 'd2-r-attention',
    code: 'D2-R',
    title_ar: 'اختبار د2 لشطب الرموز وقياس سرعة ودقة الانتباه المستمر (d2-R Attention)',
    title_fr: 'Test d\'Attention Concentrée d2-R',
    category: 'adhd',
    category_label: 'التركيز والانتباه المستمر',
    age_range: '9 - 60 سنة',
    duration: '10 دقائق (موقوت بالثواني)',
    dimensions: ['السرعة الإجمالية للمعالجة (TN)', 'نسبة الدقة وشطب الحرف d بنقطتين', 'أخطاء الحذف وأخطاء الإضافة', 'مؤشر التركيز الصافي (CP)'],
    description: 'أداة ورقية ورقمية لقياس طاقة الانتباه والقدرة على المحافظة على التركيز تحت الضغط والجهد المستمر.',
    cutoff: 'درجات معيارية للسرعة والدقة - الرتبة المئينية < 16 تشير إلى تشتت انتباهي واضح',
    color: 'from-blue-600 to-indigo-800',
    icon: Clock
  },
  {
    id: 'tower-london',
    code: 'TOWER-LOND',
    title_ar: 'اختبار برج لندن للتخطيط وحل المشكلات المعقدة (Tower of London - Shallice)',
    title_fr: 'Test de la Tour de Londres (Planification & Stratégie)',
    category: 'adhd',
    category_label: 'التخطيط والوظائف التنفيذية',
    age_range: '7 سنوات فما فوق والبالغون',
    duration: '20 دقيقة',
    dimensions: ['تحريك الكرات الملونة وفق نموذج محدد', 'عدد الحركات المنجزة مقارنة بالحد الأدنى', 'زمن التخطيط قبل الحركة الأولى', 'انتهاك القواعد والتسرع'],
    description: 'يقيس كفاءة التخطيط الاستراتيجي المستقبلي والمرونة في التفكير وحل المشكلات.',
    cutoff: 'مجموع درجات الدقة والزمن - الفشل في حل المسائل متعددة الخطوات يشير إلى عجز في التخطيط التنفيذي',
    color: 'from-teal-600 to-cyan-700',
    icon: Brain
  },
  {
    id: 'brief-2',
    code: 'BRIEF-2',
    title_ar: 'مقياس السلوك التنفيذي في الحياة اليومية للأطفال والمراهقين (BRIEF-2)',
    title_fr: 'Behavior Rating Inventory of Executive Function - 2nd Edition',
    category: 'adhd',
    category_label: 'الوظائف التنفيذية السلوكية',
    age_range: '5 - 18 سنة',
    duration: '15 دقيقة',
    dimensions: ['مؤشر الضبط السلوكي (الكبح، التنقل، ضبط الانفعال)', 'مؤشر الضبط المعرفي (المبادأة، الذاكرة العاملة، التخطيط، المراقبة)'],
    description: 'يقيم كيف تنعكس صعوبات الوظائف التنفيذية في المنزل والمدرسة من خلال تقرير الأسرة والمعلمين.',
    cutoff: 'T-Score > 65 على مؤشر GEC يشير إلى خلل وظيفي تنفيذي مؤثر على الأداء اليومي',
    color: 'from-pink-600 to-purple-800',
    icon: Activity
  },
  {
    id: 'bhk-dysgraphie',
    code: 'BHK-DYS',
    title_ar: 'مقياس فحص عسر الكتابة وجودة وسرعة خط اليد للأطفال (BHK - Charles et al.)',
    title_fr: 'Échelle d\'Évaluation Rapide de l\'Écriture chez l\'Enfant (BHK)',
    category: 'learning',
    category_label: 'عسر الكتابة (Dysgraphie)',
    age_range: '6 - 12 سنة (من التحضيري إلى المتوسط)',
    duration: '5 دقائق كتابة مستمرة',
    dimensions: ['حجم الحروف واضطراب الأسطر', 'الضغط على الورقة والارتجاف', 'تشويه الحروف وتصادم الكلمات', 'سرعة الكتابة وعدد الحروف المكتوبة في 5 دقائق'],
    description: 'المقياس السريري الأول لتشخيص الديسغرافيا واضطراب الكتابة اليدوية وتحديد ما إذا كان الخط وظيفياً أم معيقاً.',
    cutoff: 'درجة التدهور الخطي > 21 تشير إلى عسر كتابة مؤكد (Dysgraphie avérée)',
    color: 'from-emerald-600 to-teal-700',
    icon: BookOpen
  },
  {
    id: 'bale-lecture',
    code: 'BALE-EVAL',
    title_ar: 'بطارية التحليل اللساني لصعوبات القراءة والتهجئة والفهم (BALE)',
    title_fr: 'Batterie Analytique du Langage Écrit (BALE)',
    category: 'learning',
    category_label: 'صعوبات التعلم والأكاديمي',
    age_range: '7 - 12 سنة',
    duration: '35 دقيقة',
    dimensions: ['قراءة نصوص قصصية وعلمية', 'الفهم القرائي الصريح والضمني', 'الإملاء الاسترجاعي والإملاء التركيبي', 'التفسير الدلالي للجمل'],
    description: 'أداة تشخيصية فارقة لتمييز صعوبة القراءة الناتجة عن فك الشفرة عن صعوبة الفهم القرائي المجرد.',
    cutoff: 'مقارنة بنسب الإنجاز لكل مستوى دراسي (من السنة الأولى ابتدائي إلى الأولى متوسط)',
    color: 'from-amber-600 to-orange-700',
    icon: BookOpen
  },

  // --- 4. COGNITIVE & INTELLIGENCE (الذكاء والقدرات العقلية) ---
  {
    id: 'wisc-5',
    code: 'WISC-V',
    title_ar: 'مقياس وكسلر لذكاء الأطفال والقدرات العقلية العامة - الإصدار الخامس',
    title_fr: 'Échelle d\'Intelligence de Wechsler pour Enfants - 5ème Édition',
    category: 'psychology',
    category_label: 'القدرات العقلية والذكاء',
    age_range: '6 - 16 سنة و 11 شهراً',
    duration: '60 - 90 دقيقة',
    dimensions: ['الفهم اللفظي (VCI)', 'الاستدلال البصري المكاني (VSI)', 'الاستدلال المائع (FRI)', 'الذاكرة العاملة (WMI)', 'سرعة المعالجة (PSI)'],
    description: 'البطارية النفسية الشاملة لتحديد معامل الذكاء العام (FSIQ) وتشخيص التأخر الذهني والموهبة الفكرية وتحديد نقاط القوة والضعف.',
    cutoff: '< 70: تأخر ذهني | 90-109: متوسط طبيعي | 120-129: متفوق | > 130: موهبة عقلية فائقة (HPI)',
    color: 'from-indigo-600 to-violet-800',
    icon: Zap
  },
  {
    id: 'wppsi-4',
    code: 'WPPSI-IV',
    title_ar: 'مقياس وكسلر لذكاء الطفولة المبكرة وما قبل التمدرس (WPPSI-IV)',
    title_fr: 'Wechsler Preschool and Primary Scale of Intelligence - 4th Edition',
    category: 'psychology',
    category_label: 'ذكاء الطفولة المبكرة',
    age_range: 'سنتان و 6 أشهر - 7 سنوات و 7 أشهر',
    duration: '45 دقيقة',
    dimensions: ['معامل الفهم اللفظي للأطفال الصغار', 'القدرة البصرية المكانية بالأشكال والمكعبات', 'الذاكرة العاملة المصورة', 'سرعة الاستجابة الحركية'],
    description: 'مقياس ذكاء مكيف ومبسط للصغار يعتمد على الألعاب والمكعبات الملونة والصور الجاذبة دون إجهاد الطفل.',
    cutoff: 'حساب معامل الذكاء العام (QI Total) ومؤشر الكفاءة المعرفية المبكرة (IPC)',
    color: 'from-purple-600 to-indigo-700',
    icon: Smile
  },
  {
    id: 'raven-cpm',
    code: 'RAVEN-CPM',
    title_ar: 'مصفوفات ريفن المتتابعة الملونة للذكاء غير اللفظي (Raven CPM)',
    title_fr: 'Matrices Progressives Colorées de Raven (CPM)',
    category: 'psychology',
    category_label: 'الذكاء غير اللفظي والمحايد',
    age_range: '5 - 11 سنة والمسنون',
    duration: '20 - 30 دقيقة',
    dimensions: ['36 مصفوفة ملونة مقسمة على 3 مجموعات (A, Ab, B)', 'إكمال النمط البصري الناقص', 'الاستدلال التجريدي والعلاقات الفضائية'],
    description: 'المقياس المثالي لقياس الذكاء والاستدلال التجريدي المحايد ثقافياً ولغوياً (ممتاز لحالات التوحد وتأخر الكلام).',
    cutoff: 'الرتبة المئينية: > 95% عبقري | 75-90% فوق المتوسط | 25-75% متوسط طبيعي | < 5% تأخر عقلي',
    color: 'from-blue-600 to-cyan-800',
    icon: Eye
  },
  {
    id: 'goodenough-draw',
    code: 'DRAW-PERSON',
    title_ar: 'اختبار رسم الرجل للنضج العقلي والمعرفي السريع (Goodenough-Harris)',
    title_fr: 'Test du Bonhomme (Dessin de la Figure Humaine)',
    category: 'psychology',
    category_label: 'النضج العقلي والمعرفي السريع',
    age_range: '3 - 13 سنة',
    duration: '10 - 15 دقيقة',
    dimensions: ['وجود وتناسق الرأس والوجه والعينين', 'الجذع والأطراف والملابس والأصابع', 'النسب والتفاصيل الثنائية والعمق'],
    description: 'اختبار كلاسيكي ممتع للأطفال يقيس النضج العقلي والتطور الإدراكي عبر 73 معياراً دقيقاً في تفاصيل الرسم.',
    cutoff: 'تحويل النقاط المحققة إلى عمر عقلي (Âge Mental) وحساب نسبة الذكاء التقريبية',
    color: 'from-emerald-500 to-teal-700',
    icon: Sparkles
  },
  {
    id: 'figure-rey',
    code: 'FIGURE-REY',
    title_ar: 'رائز الشكل المعقد لراي للإدراك البصري المكاني والذاكرة (Figure de Rey A & B)',
    title_fr: 'Test de la Figure Complexe de Rey - Forme A & B',
    category: 'psychology',
    category_label: 'الإدراك البصري والذاكرة',
    age_range: '4 سنوات فما فوق والبالغون',
    duration: '15 دقيقة (نسخ فوري + استرجاع بعد 3 دقائق)',
    dimensions: ['طريقة واستراتيجية النسخ (البدء بالهيكل المركزي أم التفاصيل)', 'دقة وموقع العناصر الـ 18 المكونة للشكل', 'الذاكرة البصرية التراجعية بعد 3 دقائق'],
    description: 'يكشف اضطرابات البراكسيا البصرية المكانية والديسبركسيا (Dyspraxie) وقدرة الدماغ على التخطيط والحفظ.',
    cutoff: 'الدرجة القصوى 36 نقطة - الرتبة المئينية للزمن ودقة الرسم تحدد مستوى النضج الإدراكي',
    color: 'from-indigo-700 to-purple-900',
    icon: Layers
  },
  {
    id: 'nepsy-2',
    code: 'NEPSY-II',
    title_ar: 'بطارية التقييم النمائي العصبي الشاملة للوظائف الدماغية للأطفال (NEPSY-II)',
    title_fr: 'Bilan Neuropsychologique de l\'Enfant - 2ème Édition',
    category: 'psychology',
    category_label: 'التقييم النيوروبسيكولوجي',
    age_range: '3 - 16 سنة',
    duration: '45 - 90 دقيقة (اختبارات معيارية مجزأة)',
    dimensions: ['الانتباه والوظائف التنفيذية', 'اللغة والمعالجة الفونولوجية', 'الذاكرة والتعلم', 'الإدراك الاجتماعي (نظرية العقل وتعرف الوجوه)', 'المعالجة البصرية المكانية والمهارات الحركية الحسية'],
    description: 'البطارية النيوروبسيكولوجية الأكثر شمولاً في العالم لتقييم صعوبات التعلم واضطرابات الدماغ النمائية.',
    cutoff: 'درجات معيارية مقاسة لكل مجال مع كشف فوري للاضطرابات النمائية العصبية الدقيقة',
    color: 'from-violet-600 to-purple-800',
    icon: Brain
  },
  {
    id: 'cms-memory',
    code: 'CMS',
    title_ar: 'مقياس الذاكرة والتعلم النمائي للأطفال (Children\'s Memory Scale - CMS)',
    title_fr: 'Échelle de Mémoire pour Enfants (CMS)',
    category: 'psychology',
    category_label: 'الذاكرة والتعلم',
    age_range: '5 - 16 سنة',
    duration: '35 - 45 دقيقة',
    dimensions: ['الذاكرة اللفظية والسمعية (قصص وكلمات)', 'الذاكرة البصرية (وجوه ومسارات مكانية)', 'الاسترجاع الفوري والاسترجاع المؤجل (بعد 30 دقيقة)', 'الانتباه والتركيز في التخزين'],
    description: 'تقييم معمق لقدرات الحفظ والاسترجاع السمعي والبصري وتحديد أسباب نسيان الدروس عند المتمدرسين.',
    cutoff: 'معامل الذاكرة العام (General Memory Index) بمتوسط 100 وانحراف معياري 15',
    color: 'from-teal-600 to-cyan-800',
    icon: BookOpen
  },

  // --- 5. CLINICAL PSYCHOLOGY & AFFECT (علم النفس العيادي والصحة الانفعالية) ---
  {
    id: 'bdi-2-beck',
    code: 'BDI-II',
    title_ar: 'مقياس بيك للاكتئاب السريري - الإصدار الثاني (Beck Depression Inventory)',
    title_fr: 'Inventaire de Dépression de Beck - 2ème Édition',
    category: 'psychology',
    category_label: 'الاكتئاب والصحة النفسية',
    age_range: '13 سنة فما فوق والبالغون',
    duration: '10 دقائق',
    dimensions: ['المشاعر الحزينة والتشاؤم والذنب', 'الأفكار الانتحارية وفقدان المتعة', 'الأعراض الجسدية (النوم، الشهية، الإرهاق)', 'تدني تقدير الذات وصعوبة اتخاذ القرار'],
    description: 'المقياس الأكثر استخداماً في الطب النفسي لتقدير وجود وشدة الأعراض الاكتئابية ورصد مؤشرات الخطورة.',
    cutoff: '0-13: طبيعي | 14-19: اكتئاب خفيف | 20-28: اكتئاب متوسط | 29-63: اكتئاب حاد وشديد',
    color: 'from-slate-700 to-indigo-900',
    icon: Frown
  },
  {
    id: 'gad-7-anxiety',
    code: 'GAD-7',
    title_ar: 'مقياس اضطراب القلق العام والتوتر اليومي (Generalized Anxiety Disorder 7)',
    title_fr: 'Échelle d\'Anxiété Généralisée à 7 Items (GAD-7)',
    category: 'psychology',
    category_label: 'القلق والتوتر العصبي',
    age_range: '12 سنة فما فوق والبالغون',
    duration: '5 دقائق',
    dimensions: ['الشعور بالتوتر والعصبية والتململ', 'عدم القدرة على إيقاف القلق', 'القلق المفرط بشأن أحداث مختلفة', 'صعوبة الاسترخاء والخوف من وقوع مصيبة'],
    description: 'مقياس موجز ومعتمد عالمياً لفرز وتقدير شدة القلق والتوتر النفسي في الرعاية الأولية والعيادية.',
    cutoff: '0-4: قلق ضئيل | 5-9: قلق خفيف | 10-14: قلق متوسط يستدعي المتابعة | 15-21: قلق حاد وشديد',
    color: 'from-amber-600 to-rose-700',
    icon: ShieldAlert
  },
  {
    id: 'rcmas-stai',
    code: 'RCMAS',
    title_ar: 'مقياس القلق الصريح للأطفال والمراهقين (RCMAS - Reynolds & Richmond)',
    title_fr: 'Échelle d\'Anxiété Manifeste pour Enfants Révisée',
    category: 'psychology',
    category_label: 'قلق الأطفال والمراهقين',
    age_range: '6 - 19 سنة',
    duration: '15 دقيقة',
    dimensions: ['القلق الفسيولوجي والأعراض الجسدية (ضربات القلب والمغص)', 'الانشغال الزائد بالأفكار والمخاوف', 'القلق الاجتماعي والمدرسي', 'مقياس الكذب والميل لإرضاء الآخرين'],
    description: 'يكشف بدقة ما يعانيه الطفل في صمت من مخاوف وقلق الامتحانات والتوترات الاجتماعية.',
    cutoff: 'الدرجة التائية T-Score > 60 تشير إلى مستوى قلق مرتفع دال يستدعي التدخل النفسي',
    color: 'from-rose-500 to-purple-700',
    icon: HeartPulse
  },
  {
    id: 'rosenberg-esteem',
    code: 'ROSENBERG',
    title_ar: 'مقياس روزنبرغ لتقدير الذات والثقة الشخصية (Rosenberg Self-Esteem Scale)',
    title_fr: 'Échelle d\'Estime de Soi de Rosenberg',
    category: 'psychology',
    category_label: 'تقدير الذات والثقة بالنفس',
    age_range: '10 سنوات فما فوق والبالغون',
    duration: '5 دقائق',
    dimensions: ['الشعور بالجدارة والكفاءة الشخصية', 'النظرة الإيجابية تجاه النفس', 'مشاعر الفشل أو الدونية'],
    description: '10 بنود مقننة لقياس الموقف الشامل للفرد نحو ذاته ومدى تقبله وتقديره لنفسه.',
    cutoff: '< 15: تقدير ذات منخفض جداً | 15-25: تقدير ذات طبيعي ومتزن | > 25: تقدير ذات مرتفع',
    color: 'from-emerald-600 to-teal-800',
    icon: Award
  },
  {
    id: 'trauma-pcl5',
    code: 'PCL-5',
    title_ar: 'استبيان تشخيص اضطراب كرب ما بعد الصدمة (PCL-5 / TraumaQ)',
    title_fr: 'Posttraumatic Stress Disorder Checklist for DSM-5',
    category: 'psychology',
    category_label: 'الصدمات النفسية (PTSD)',
    age_range: 'المراهقون والبالغون',
    duration: '15 دقيقة',
    dimensions: ['أعراض استرجاع الصدمة والكوابيس', 'التجنب المستمر للمثيرات والذكريات', 'التغيرات السلبية في المزاج والأفكار', 'فرط الاستثارة والتحفز وسهولة الفزع'],
    description: 'مقياس DSM-5 الرسمي لتقييم أعراض الصدمة بعد الحوادث أو الفقدان أو العنف.',
    cutoff: 'درجة القطع السريرية: 31-33 نقطة تشير إلى تشخيص مرجح لاضطراب ما بعد الصدمة',
    color: 'from-slate-800 to-rose-900',
    icon: ShieldAlert
  },
  {
    id: 'tat-cat-projective',
    code: 'TAT-CAT',
    title_ar: 'اختبار تفهم الموضوع الإسقاطي للأطفال والراشدين (TAT & CAT - Murray)',
    title_fr: 'Thematic Apperception Test & Children Apperception Test',
    category: 'psychology',
    category_label: 'الاختبارات الإسقاطية والتحليلية',
    age_range: 'الأطفال من 3 سنوات فما فوق والبالغون',
    duration: '45 دقيقة',
    dimensions: ['تحليل البطل وتماهي المفحوص معه', 'الحاجات والضغوط والصراعات النفسية اللاواعية', 'نوعية العلاقات الموضوعية والأسرية', 'آليات الدفاع ونهايات القصص'],
    description: 'لوحات وبطاقات مصورة غامضة تحفز المفحوص على تأليف قصص تكشف بنيته النفسية وصراعاته الداخلية.',
    cutoff: 'تحليل كيفي إكلينيكي لدينامية الشخصية والميكانيزمات الدفاعية وفق المدرسة التحليلية',
    color: 'from-purple-800 to-indigo-950',
    icon: Eye
  },
  {
    id: 'patte-noire',
    code: 'PATTE-NOIRE',
    title_ar: 'رائز الساق السوداء الإسقاطي للتحليل النفسي للأطفال (Louis Corman)',
    title_fr: 'Test Patte-Noire de Louis Corman',
    category: 'psychology',
    category_label: 'التحليل النفسي الإسقاطي',
    age_range: '4 - 12 سنة',
    duration: '35 دقيقة',
    dimensions: ['مغامرات الخنزير الصغير ذو الساق السوداء', 'الصراع الأوديبي والغيرة بين الإخوة', 'تثبيتات المرحلة الفمية والشرجية', 'العقاب والشعور بالذنب والعدوانية'],
    description: 'الرائز الإسقاطي الشهير في العيادات النفسية للأطفال في الجزائر وفرنسا لاستكشاف العقد النفسية العميقة.',
    cutoff: 'تحليل شبكة موضوعات الصراع (Thèmes) والميول التقمصية وديناميات الأسرة',
    color: 'from-amber-800 to-slate-900',
    icon: Sparkles
  },

  // --- 6. PSYCHOMOTRICITY & SENSORY MOTOR (النفسي-حركي والتوازن) ---
  {
    id: 'm-abc-2',
    code: 'M-ABC-2',
    title_ar: 'بطارية تقييم الحركة والتناسق الحركي للأطفال (Henderson & Sugden)',
    title_fr: 'Movement Assessment Battery for Children - 2nd Edition',
    category: 'psychomotricite',
    category_label: 'النفسي حركي والتناسق (TDC)',
    age_range: '3 - 16 سنة',
    duration: '30 - 45 دقيقة',
    dimensions: ['البراعة اليدوية (إدخال الأوتاد، نظم الخرز، تتبع المسار)', 'التصويب والالتقاط (رمي الكيس، التقاط الكرة باليدين)', 'التوازن الساكن والديناميكي (الوقوف على قدم واحدة، المشي كعب لأصابع)'],
    description: 'الأداة المعيارية الدولية لتشخيص اضطراب التناسق النمائي (TDC / Dyspraxie motrice).',
    cutoff: 'الرتبة المئينية < 5%: اضطراب حركي شديد مؤكد | 6-15%: منطقة خطر تتطلب المتابعة',
    color: 'from-emerald-600 to-teal-700',
    icon: Activity
  },
  {
    id: 'lateralite-auzias',
    code: 'AUZIAS-LAT',
    title_ar: 'رائز الجانبية والهيمنة اليدوية والبصرية والسمعية والطرفية (Marguerite Auzias)',
    title_fr: 'Épreuve de Latéralité Usuelle de M. Auzias',
    category: 'psychomotricite',
    category_label: 'الجانبية والهيمنة الدماغية',
    age_range: '4 - 11 سنة',
    duration: '15 دقيقة',
    dimensions: ['الجانبية اليدوية العفوية والمكتسبة (10 مهام: القص، التوزيع، تمشيط الشعر)', 'الجانبية البصرية (النظر في الأنبوب/الثقب)', 'الجانبية السمعية (سماع دقات الساعة)', 'الجانبية الطرفية (ركل الكرة)'],
    description: 'يكشف الجانبية المتصالبة (Latéralité croisée) أو غير المستقرة المسؤولة عن صعوبات القراءة وعكس الحروف.',
    cutoff: 'حساب حاصل الجانبية (Quotient de Latéralité): يميني متجانس / يساري متجانس / متصالب',
    color: 'from-teal-600 to-cyan-800',
    icon: Scale
  },
  {
    id: 'berges-lezine',
    code: 'BERGES-LEZINE',
    title_ar: 'رائز المخطط الجسمي وتقليد الحركات الجسدية (Bergès & Lézine)',
    title_fr: 'Test d\'Imitation de Gestes (Schéma Corporel)',
    category: 'psychomotricite',
    category_label: 'المخطط الجسمي والوعي الجسدي',
    age_range: '3 - 8 سنوات',
    duration: '20 دقيقة',
    dimensions: ['تقليد الحركات البسيطة (اليدين والذراعين)', 'تقليد الحركات المعقدة والمتعاكسة في الفضاء', 'الوعي باليمين واليسار على جسم الذات وعلى جسم الآخر'],
    description: 'يقيس مدى إدراك الطفل لحدود جسده وقدرته على إعادة إنتاج أوضاع فراغية بدقة.',
    cutoff: 'مقارنة الدرجة بالعمر النمائي للمخطط الجسمي لكشف عسر الإدراك الحركي الفراغي',
    color: 'from-blue-600 to-indigo-700',
    icon: User
  },
  {
    id: 'orientation-spatio',
    code: 'SPATIO-TEMP',
    title_ar: 'رائز التنظيم والتوجه المكاني والزماني للأطفال (Piaget & Head Test)',
    title_fr: 'Épreuve d\'Orientation Spatio-Temporelle',
    category: 'psychomotricite',
    category_label: 'الفضاء والزمان والتسلسل',
    age_range: '5 - 12 سنة',
    duration: '20 دقيقة',
    dimensions: ['مفاهيم فوق/تحت، يمين/يسار، أمام/خلف', 'إدراك الفترات الزمنية (قبل/بعد، أيام الأسبوع، الفصول)', 'إعادة إنتاج الإيقاعات الزمنية المنقورة باليد'],
    description: 'يحدد أسباب صعوبة الانتقال بين أسطر القراءة وخلط الحروف المتشابهة (ب/ت/ث، d/b).',
    cutoff: 'تحديد ما إذا كان الطفل يمتلك تحكماً فضائياً وزمانياً ملائماً لمستواه الدراسي',
    color: 'from-indigo-600 to-purple-800',
    icon: Layers
  },
];

// =========================================================================
// CLINICAL THERAPY EXERCISES & PROTOCOLS (+16 HOME & CLINICAL PROTOCOLS)
// =========================================================================
export const CLINICAL_PROTOCOLS_CATALOG = [
  {
    id: 'ex-oral-motor',
    title: 'برنامج تقوية عضلات النطق والفم واللسان (Oral Motor Protocol)',
    category: 'orthophony',
    category_label: 'الأرطوفونيا والنطق',
    target: 'علاج الديسلثريا، اضطراب مخارج الحروف، وتقوية عضلات المضغ والبلع',
    difficulty: 'مبتدئ إلى متوسط',
    frequency: '3 مرات أسبوعياً (15 دقيقة)',
    materials: 'مرآة تدريب، بطاقات صور الحركات، خافض لسان طبي',
    steps: [
      'تمرين رفع وخفض اللسان نحو سقف الحلق والفك السفلي مع التثبيت 5 ثوانٍ.',
      'تمرين تحريك اللسان دائرياً حول الشفتين مع المقاومة الخفيفة.',
      'تمرين نفخ الخدين بالتناوب وحبس الهواء لتحسين الإغلاق الشفوي.',
      'تمرين اهتزاز الشفتين واللسان لتهيئة نطق صوت الراء /r/ والأصوات الانفجارية.'
    ],
    color: 'from-rose-500 to-amber-600'
  },
  {
    id: 'ex-easy-onset',
    title: 'تقنية البداية السهلة وتمديد الأصوات لمرضى التأتأة (Easy Onset & Prolongation)',
    category: 'fluency',
    category_label: 'طلاقة النطق والتأتأة',
    target: 'تقليل الوقفات اللاإرادية والتشنج الحنجري في بداية الكلمات',
    difficulty: 'متوسط إلى متقدم',
    frequency: 'يومياً (10 دقائق صباحاً ومساءً)',
    materials: 'مؤقت إيقاعي، قائمة كلمات تبدأ بحروف لينة وحروف مد',
    steps: [
      'أخذ نفس بطني عميق مع استرخاء الكتفين والحنجرة.',
      'إخراج صوت خافت ومستمر مثل /h/ أو الهمس قبل نطق الكلمة المستهدفة.',
      'تمديد الصوت الصامت الأول لمدة ثانيتين برفق دون ضغط عضلي.',
      'دمج التقنية في جمل قصيرة ثم الحوار التفاعلي التلقائي.'
    ],
    color: 'from-amber-500 to-orange-600'
  },
  {
    id: 'ex-pecs-schedule',
    title: 'نظام التواصل بالصور والروتين البصري (PECS Phase I - III)',
    category: 'autism',
    category_label: 'التوحد وتعديل السلوك',
    target: 'تطوير التواصل الوظيفي التلقائي والطلب التعبيري لأطفال طيف التوحد',
    difficulty: 'مبتدئ',
    frequency: 'مستمر خلال اليوم العلاجي والمنزلي',
    materials: 'كتاب التواصل PECS، بطاقات الأطعمة والألعاب والأنشطة',
    steps: [
      'المرحلة 1: التدريب على إعطاء البطاقة للمدرب للحصول على المعزز المفضل.',
      'المرحلة 2: زيادة المسافة والبحث عن كتاب التواصل والوصول للمتلقي.',
      'المرحلة 3: التمييز البصري بين بطاقتين (شيء مرغوب وشيء غير مرغوب).',
      'بناء شريط الجملة التعبيرية "أنا أريد + [البطاقة]".'
    ],
    color: 'from-blue-600 to-indigo-600'
  },
  {
    id: 'ex-phonological-blend',
    title: 'تدريب الوعي الفونولوجي والدمج الصوتي (Phonological Blending)',
    category: 'learning',
    category_label: 'صعوبات التعلم والديسلكسيا',
    target: 'تحسين سرعة القراءة والتهجئة والتمييز بين المقاطع الصوتية المتشابهة',
    difficulty: 'متوسط',
    frequency: '4 مرات أسبوعياً (20 دقيقة)',
    materials: 'مكعبات الأصوات الملونة، بطاقات الكلمات المجزأة',
    steps: [
      'تفكيك الكلمة المسموعة إلى أصوات منفردة (مثال: ك - ت - ا - ب).',
      'دمج الأصوات المسموعة بسرعة لتكوين الكلمة الصحيحة.',
      'التعرف على الصوت الأولي والأوسط والأخير في الكلمات.',
      'حذف أو استبدال صوت لتكوين كلمة جديدة (التلاعب الفونيمي).'
    ],
    color: 'from-emerald-500 to-teal-600'
  },
  {
    id: 'ex-attention-stroop',
    title: 'تمارين تعزيز الانتباه الانتقائي وكبح الاندفاعية (Stroop & Inhibition)',
    category: 'adhd',
    category_label: 'تشتت الانتباه وفرط الحركة',
    target: 'تنمية الوظائف التنفيذية والتحكم الذاتي وتأخير الاستجابة الاندفاعية',
    difficulty: 'متوسط إلى متقدم',
    frequency: '3 مرات أسبوعياً',
    materials: 'بطاقات شتروب الملونة، تطبيق المؤقت البصري',
    steps: [
      'قراءة لون الكلمة المكتوبة بدلاً من قراءة الكلمة نفسها (تأثير شتروب).',
      'تمرين الإيقاف والانطلاق (Go / No-Go) عند ظهور الإشارة الخضراء أو الحمراء.',
      'البحث البصري عن الأشكال المتطابقة في مصفوفة مشتتة زمنياً.',
      'تمرين الذاكرة العاملة التراجعية (تكرار الأرقام بالترتيب العكسي).'
    ],
    color: 'from-purple-600 to-pink-600'
  },
  {
    id: 'ex-breathing-relaxation',
    title: 'برنامج التنفس الحجابي والاسترخاء العضلي التدريجي (Jacobson Relaxation)',
    category: 'psychology',
    category_label: 'علم النفس والقلق السلوكي',
    target: 'خفض مستويات القلق والتوتر المصاحب للجلسات والتأتأة والامتحانات',
    difficulty: 'مبتدئ',
    frequency: 'يومياً قبل النوم وعند الشعور بالتوتر',
    materials: 'بيئة هادئة، إرشادات صوتية مهدئة',
    steps: [
      'الاستلقاء أو الجلوس المريح مع وضع اليد على البطن وأخرى على الصدر.',
      'أخذ شهيق عميق من الأنف لمدة 4 ثوانٍ مع انتفاخ البطن.',
      'حبس النفس لمدة ثانيتين ثم إخراج الزفير ببطء من الفم لمدة 6 ثوانٍ.',
      'شد عضلات اليدين والوجه ثم إرخائها تدريجياً لملاحظة الفرق في الراحة.'
    ],
    color: 'from-cyan-600 to-blue-700'
  },
  {
    id: 'ex-bilateral-balance',
    title: 'مسارات التوازن الحركي والتناسق الثنائي (Bilateral Coordination Tracks)',
    category: 'psychomotricite',
    category_label: 'التأهيل النفسي الحركي',
    target: 'تطوير التوازن الحركي، التوافق العضلي العصبي، وعلاج عسر الحركة (Dyspraxie)',
    difficulty: 'متوسط',
    frequency: '3 مرات أسبوعياً (25 دقيقة)',
    materials: 'ألواح التوازن الخشبية، دوائر حركية أرضية، كرات مطاطية',
    steps: [
      'المشي على خط مستقيم ثم خط متعرج مع وضع كعب القدم أمام أصابع القدم الأخرى.',
      'الوقوف على قدم واحدة على لوح التوازن لمدة 10 ثوانٍ مع إغلاق العينين.',
      'تبادل رمي والتقاط الكرة بكلتا اليدين أثناء القفز داخل الدوائر الأرضية.',
      'تمارين الزحف المتقاطع المعاكس (اليد اليمنى مع الركبة اليسرى والعكس).'
    ],
    color: 'from-emerald-600 to-teal-700'
  },
  {
    id: 'ex-social-skills',
    title: 'تدريب المهارات الاجتماعية والتواصل البصري وتبادل الأدوار (Social Stories)',
    category: 'autism',
    category_label: 'المهارات الاجتماعية والتواصل',
    target: 'تطوير المبادأة في المحادثة، فهم الإشارات غير اللفظية، والاندماج المدرسي',
    difficulty: 'متوسط',
    frequency: 'مرتان أسبوعياً',
    materials: 'قصص اجتماعية مصورة، بطاقات تعابير الوجه، ألعاب الأدوار',
    steps: [
      'قراءة القصة الاجتماعية حول "كيف أحيي زملائي وأطلب اللعب معهم".',
      'تمثيل الأدوار (Role-playing) وتدريب الطفل على التواصل البصري لمدة 5 ثوانٍ.',
      'تفسير تعابير الوجه الأربعة الأساسية (سعيد، حزين، غاضب، خائف).',
      'تدريب على قاعدة "انتظار الدور" في الألعاب الجماعية باستخدام بطاقة الدور.'
    ],
    color: 'from-indigo-600 to-blue-700'
  },
  {
    id: 'ex-working-memory-dual',
    title: 'تدريب الذاكرة العاملة المزدوجة السمعية والبصرية (Dual N-Back Protocol)',
    category: 'adhd',
    category_label: 'الذاكرة العاملة والتركيز',
    target: 'توسيع سعة التخزين المؤقت في الذاكرة ومقاومة النسيان السريع أثناء الحفظ',
    difficulty: 'متقدم',
    frequency: 'يومياً (15 دقيقة)',
    materials: 'شبكة أرقام وحروف، تسلسل بطاقات ملونة',
    steps: [
      'المستوى 1: تكرار 3 أرقام مسموعة بنفس الترتيب، ثم بالترتيب العكسي.',
      'المستوى 2: تذكر مكان المربع المضاء قبل خطوة واحدة (1-Back).',
      'المستوى 3: الاستماع لقائمة كلمات وتحديد الكلمة التي بدأت بحرف محدد.',
      'المستوى 4: تنفيذ تعليمتين مركبتين متتاليتين دون إعادة التوجيه.'
    ],
    color: 'from-purple-600 to-indigo-800'
  },
  {
    id: 'ex-pincer-grasp',
    title: 'تمارين تقوية عضلات الأصابع والقبض الثلاثي لمسك القلم (Pincer Grasp)',
    category: 'psychomotricite',
    category_label: 'عسر الكتابة والحركية الدقيقة',
    target: 'علاج إجهاد اليد أثناء الكتابة وتحسين جودة ووضوح الخط والتحكم بالقلم',
    difficulty: 'مبتدئ إلى متوسط',
    frequency: '4 مرات أسبوعياً (15 دقيقة)',
    materials: 'صلصال طبي بمقاومات مختلفة، ملاقط خشبية، خرز، مقص أمان',
    steps: [
      'عجن وضغط الصلصال الطبي بالأصابع الثلاثة الرئيسية (الإبهام والسبابة والوسطى).',
      'التقاط الكرات الصغيرة بواسطة الملقط ونقلها إلى أوعية ملونة متطابقة.',
      'قص أوراق تتبع الخطوط المستقيمة والمنحنية بالمقص الطبي المساعد.',
      'تلوين داخل مساحات ضيقة دون الخروج عن الإطار المحدد بقلم سميك مريح.'
    ],
    color: 'from-teal-600 to-emerald-700'
  },
  {
    id: 'ex-token-behavior',
    title: 'نظام اللوحة الرمزية والتعزيز السلوكي المنزلي (Token Economy Board)',
    category: 'autism',
    category_label: 'تعديل السلوك والتحفيز',
    target: 'تقليل نوبات العناد وزيادة الامتثال للمهام اليومية والدراسية في المنزل',
    difficulty: 'مبتدئ',
    frequency: 'مستمر يومياً',
    materials: 'لوحة نجوم مغناطيسية، صور المكافآت المرغوبة',
    steps: [
      'الاتفاق مع الطفل مسبقاً على السلوك الإيجابي المطلوب (مثال: الجلوس 15 دقيقة لحل الواجب).',
      'منح نجمة أو رمز فوري عند إنجاز المهمة بنجاح مع التعزيز اللفظي.',
      'استبدال 5 نجوم بمكافأة متفق عليها (مثال: نصف ساعة لعب مفضل أو نزهة).',
      'عدم سحب النجوم المكتسبة أبداً لتجنب الإحباط، والتركيز على التعزيز الإيجابي.'
    ],
    color: 'from-amber-500 to-pink-600'
  },
  {
    id: 'ex-auditory-discrimination',
    title: 'تدريب التمييز السمعي للأصوات المتشابهة في بيئة ضوضائية (Auditory Training)',
    category: 'orthophony',
    category_label: 'التمييز السمعي واللغة',
    target: 'معالجة الخلط بين الحروف المتقاربة في المخرج (س/ش، ك/ق، د/ط)',
    difficulty: 'متوسط',
    frequency: '3 مرات أسبوعياً',
    materials: 'سماعات رأس، تسجيلات كلمات ثنائية صغرى (Paires Minimales)',
    steps: [
      'الاستماع لكلمتين متقاربتين (مثال: سَمين / شَمين) وتحديد الصوت المختلف.',
      'رفع البطاقة المناسبة عند سماع الكلمة المستهدفة بين أصوات مشتتة.',
      'تكرار الكلمات تحت خلفية ضوضائية خفيفة لمحاكاة بيئة القسم المدرسي.',
      'الربط بين الصوت المسموع والحرف المكتوب لترسيخ الذاكرة الفونولوجية.'
    ],
    color: 'from-blue-600 to-teal-700'
  },
  {
    id: 'ex-resonant-voice',
    title: 'برنامج الصوت الرنان وتقليل الجهد الحنجري (Resonant Voice Therapy)',
    category: 'orthophony',
    category_label: 'التأهيل الصوتي والبحة',
    target: 'علاج بحة الصوت والإجهاد الصوتي وعقد الأحبال الصوتية (Nodules)',
    difficulty: 'متوسط',
    frequency: 'يومياً (15 دقيقة)',
    materials: 'أنبوب ماء زجاجي، نغمات صوتية مستمرة',
    steps: [
      'تمرين النفخ والهمهمة بالصوت عبر قشة في كوب ماء (Lax Vox Protocol).',
      'إصدار صوت "مِمممم" ممتد مع الشعور بالرنين والاهتزاز في جسر الأنف والشفاه.',
      'الانتقال من النغمات الأحادية إلى الكلمات اليومية مع المحافظة على خفة الصوت.',
      'تجنب الصراخ وتنظيف الحلق بحركات قاسية، وشرب كميات كافية من الماء.'
    ],
    color: 'from-rose-600 to-amber-700'
  },
  {
    id: 'ex-cbt-thought-diary',
    title: 'سجل مذكرات الأفكار التلقائية وإعادة الهيكلة المعرفية (CBT Thought Record)',
    category: 'psychology',
    category_label: 'العلاج المعرفي السلوكي',
    target: 'رصد وتعديل الأفكار الكارثية والتشوهات المعرفية المسببة للقلق والاكتئاب',
    difficulty: 'متوسط إلى متقدم',
    frequency: 'عند حدوث أي نوبة توتر أو ضيق انفعالي',
    materials: 'جدول الأعمدة الخمسة لبيك، دليل التشوهات المعرفية',
    steps: [
      'تحديد الموقف المثير (ماذا حدث بالتحديد؟ وأين ومتى؟).',
      'تحديد الفكرة التلقائية المشوهة (ماذا قلت لنفسي في تلك اللحظة؟).',
      'تسمية المشاعر الناتجة وتقييم شدتها من 0 إلى 100%.',
      'البحث عن الأدلة الواقعية المؤيدة والمعارضة لهذه الفكرة.',
      'صياغة فكرة بديلة عقلانية ومتزنة وإعادة تقييم شدة الانفعال.'
    ],
    color: 'from-purple-700 to-indigo-900'
  },
  {
    id: 'ex-dyslexia-syllabic',
    title: 'برنامج القراءة المقطعية والنصوص المتدرجة لعسر القراءة (Syllabic Reading)',
    category: 'learning',
    category_label: 'علاج الديسلكسيا',
    target: 'بناء الطلاقة القرائية وتسهيل دمج المقاطع في الكلمات متعددة المقاطع',
    difficulty: 'متوسط',
    frequency: 'يومياً (15 دقيقة قراءة موجهة)',
    materials: 'نصوص ملونة بالتناوب المقطعي، مسطرة قراءة بصرية',
    steps: [
      'تلوين مقاطع الكلمات بلونين متناوبين (مثال: المقطع الأول أزرق والثاني أحمر).',
      'تغطية الكلمات اللاحقة بمسطرة القراءة والتركيز على المقطع المنظور فقط.',
      'القراءة الثنائية المتزامنة مع الأخصائي (Choral Reading) لضبط السرعة.',
      'إعادة قراءة نفس الفقرة 3 مرات لقياس تطور سرعة القراءة بالدقائق.'
    ],
    color: 'from-amber-600 to-emerald-700'
  },
  {
    id: 'ex-spatial-time-sequence',
    title: 'برنامج التسلسل الزماني والمكاني والقصص التتابعية (Temporal Sequences)',
    category: 'psychomotricite',
    category_label: 'التنظيم المكاني الزماني',
    target: 'معالجة التشتت في إدراك تعاقب الأحداث وفهم مفاهيم (الماضي، الحاضر، والمستقبل)',
    difficulty: 'مبتدئ إلى متوسط',
    frequency: '3 مرات أسبوعياً',
    materials: 'بطاقات قصص متسلسلة (3 إلى 6 بطاقات)، جدول الأيام والشهور',
    steps: [
      'ترتيب بطاقات القصة المصورة من اليمين إلى اليسار وفق التتابع المنطقي.',
      'سرد أحداث القصة باستخدام أدوات الربط: (في البداية، ثم، بعد ذلك، وأخيراً).',
      'تحديد ما حدث "قبل" و "بعد" حدث معين في القصة.',
      'تمثيل جدول الروتين اليومي وربطه بساعة الحائط والأنشطة الواقعية.'
    ],
    color: 'from-cyan-600 to-indigo-800'
  },
];
