#!/usr/bin/env bash
# ==============================================================================
# PsyPro SaaS - Automated Custom Domain & Let's Encrypt SSL Provisioner
# Usage: sudo /usr/local/bin/provision-clinic-domain.sh <domain_name> [app_port]
# ==============================================================================

set -e

DOMAIN="$1"
APP_PORT="${2:-80}"
APP_HOST="127.0.0.1"
NGINX_AVAILABLE="/etc/nginx/sites-available"
NGINX_ENABLED="/etc/nginx/sites-enabled"
CONF_FILE="${NGINX_AVAILABLE}/clinic_${DOMAIN}.conf"
LINK_FILE="${NGINX_ENABLED}/clinic_${DOMAIN}.conf"
CERTBOT_EMAIL="admin@psypro.tech"

# 1. Validate domain argument
if [ -z "$DOMAIN" ]; then
    echo "[ERROR] Missing domain argument. Usage: $0 <domain_name>" >&2
    exit 1
fi

# Clean domain from http/https prefixes and trailing slashes
DOMAIN=$(echo "$DOMAIN" | sed -e 's|^[^/]*//||' -e 's|/.*$||' | tr '[:upper:]' '[:lower:]')

# Validate domain regex syntax
if [[ ! "$DOMAIN" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+$ ]]; then
    echo "[ERROR] Invalid domain format: $DOMAIN" >&2
    exit 1
fi

echo "[INFO] Starting automated provisioning for domain: $DOMAIN (Target App Port: $APP_PORT)..."

# Ensure directories exist
mkdir -p "$NGINX_AVAILABLE" "$NGINX_ENABLED"

# 2. Generate Nginx virtual host configuration
cat > "$CONF_FILE" <<EOF
# ==============================================================================
# PsyPro Clinic Custom Domain - ${DOMAIN}
# Auto-generated by PsyPro SSL Engine
# ==============================================================================

server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN} www.${DOMAIN};

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;

    # Gzip Compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        proxy_pass http://${APP_HOST}:${APP_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Custom-Domain ${DOMAIN};
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 90;
    }

    location ~ /\. {
        deny all;
    }
}
EOF

# 3. Create symlink to sites-enabled
ln -sf "$CONF_FILE" "$LINK_FILE"

# 4. Test initial HTTP Nginx configuration
if ! nginx -t 2>/dev/null; then
    echo "[ERROR] Initial Nginx configuration test failed. Rolling back..." >&2
    rm -f "$LINK_FILE" "$CONF_FILE"
    nginx -t 2>/dev/null && (systemctl reload nginx 2>/dev/null || nginx -s reload 2>/dev/null || true)
    exit 1
fi

# Reload Nginx so Certbot HTTP challenge can pass
(systemctl reload nginx 2>/dev/null || nginx -s reload 2>/dev/null || true)

# 5. Execute Certbot for automated Let's Encrypt SSL issuance & redirection
echo "[INFO] Requesting Let's Encrypt SSL certificate via Certbot..."
if command -v certbot >/dev/null 2>&1; then
    if certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos -m "$CERTBOT_EMAIL" --redirect --no-eff-email; then
        echo "[SUCCESS] SSL Certificate successfully issued and configured for $DOMAIN."
    else
        echo "[WARNING] Certbot SSL issuance failed for $DOMAIN. Keeping HTTP configuration active." >&2
    fi
else
    echo "[NOTICE] certbot command not found on host. Keeping HTTP Nginx configuration."
fi

# 6. Final verification & Nginx reload
if nginx -t 2>/dev/null; then
    (systemctl reload nginx 2>/dev/null || nginx -s reload 2>/dev/null || true)
    echo "[SUCCESS] Domain $DOMAIN is fully provisioned and live!"
    exit 0
else
    echo "[ERROR] Final Nginx verification failed. Rolling back..." >&2
    rm -f "$LINK_FILE" "$CONF_FILE"
    nginx -t 2>/dev/null && (systemctl reload nginx 2>/dev/null || nginx -s reload 2>/dev/null || true)
    exit 1
fi
